# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-04 16:08
from __future__ import unicode_literals

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('colour', colorful.fields.RGBColorField(colors=['#f6e1f0', '#e1f0f6', '#f0f6e1', '#f6e7e1', '#e1e6f6', '#f6f2e1'])),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_changed_date_time', models.DateTimeField(auto_now=True, verbose_name='Last Changed')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCategory',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('colour', colorful.fields.RGBColorField(colors=['#f6e1f0', '#e1f0f6', '#f0f6e1', '#f6e7e1', '#e1e6f6', '#f6f2e1'])),
                ('created_date_time', models.DateTimeField(blank=True, editable=False, verbose_name='Created')),
                ('last_changed_date_time', models.DateTimeField(blank=True, editable=False, verbose_name='Last Changed')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical category',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUrl',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('url', models.URLField(max_length=400, verbose_name='URL')),
                ('editable', models.BooleanField(verbose_name='Editable')),
                ('created_date_time', models.DateTimeField(blank=True, editable=False, verbose_name='Created')),
                ('last_changed_date_time', models.DateTimeField(blank=True, editable=False, verbose_name='Last Changed')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='laboratory_management.Category')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical url',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('url', models.URLField(max_length=400, verbose_name='URL')),
                ('editable', models.BooleanField(verbose_name='Editable')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_changed_date_time', models.DateTimeField(auto_now=True, verbose_name='Last Changed')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory_management.Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
