# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormZProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=191, null=True, verbose_name='title')),
                ('safety_level', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], null=True, verbose_name='safety level')),
                ('project_leader', models.CharField(max_length=255, null=True, verbose_name='project leader')),
                ('objectives', models.CharField(blank=True, max_length=255, null=True, verbose_name='objectives of strategy')),
                ('description', models.TextField(blank=True, help_text='Techniques, organisms, plasmids, etc.', null=True, verbose_name='Description of stratagy/performance')),
                ('donor_organims', models.CharField(blank=True, help_text='Used organisms, their risk group and safety-relevant properties', max_length=255, null=True, verbose_name='donor organisms')),
                ('potential_risk_nuc_acid', models.TextField(blank=True, help_text='Include safety-relevant properties', null=True, verbose_name='potential risks of transferred nucleic acids')),
                ('vectors', models.TextField(blank=True, help_text='Include safety-relevant properties', null=True, verbose_name='Vectors')),
                ('recipient_organisms', models.CharField(blank=True, help_text='Include risk groups and safety-relevant properties', max_length=255, null=True, verbose_name='recipient organisms')),
                ('generated_gmo', models.TextField(blank=True, help_text='Include risk groups and safety-relevant properties', null=True, verbose_name='generated GMOs')),
                ('hazard_activity', models.TextField(blank=True, null=True, verbose_name='hazard-relevant characteristics of activity')),
                ('hazards_employee', models.TextField(blank=True, null=True, verbose_name='severity and likelihood of hazards to employees and/or the environment')),
                ('beginning_work_date', models.DateField(null=True, verbose_name='beginning of work')),
                ('end_work_date', models.DateField(blank=True, null=True, verbose_name='end of work')),
            ],
        ),
        migrations.CreateModel(
            name='GenTechMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=255, null=True, verbose_name='English name')),
                ('german_name', models.CharField(max_length=255, null=True, verbose_name='German name')),
            ],
            options={
                'verbose_name_plural': 'genTech methods',
                'verbose_name': 'genTech method',
            },
        ),
        migrations.CreateModel(
            name='NucleicAcidPurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=255, null=True, verbose_name='English name')),
                ('german_name', models.CharField(max_length=255, null=True, verbose_name='German name')),
            ],
            options={
                'verbose_name_plural': 'nuclei acid purities',
                'verbose_name': 'nuclei acid purity',
            },
        ),
        migrations.CreateModel(
            name='NucleicAcidRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=255, null=True, verbose_name='English name')),
                ('german_name', models.CharField(max_length=255, null=True, verbose_name='German name')),
            ],
            options={
                'verbose_name_plural': 'nuclei acid risk potentials',
                'verbose_name': 'nuclei acid risk potential',
            },
        ),
    ]
