# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormZBaseElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('donor_organism', models.CharField(blank=True, max_length=255, null=True, verbose_name='Donor organism')),
                ('donor_organism_risk', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group')),
                ('nuc_acid_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nucleic acid type')),
                ('nuc_acid_purity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formz.NucleicAcidPurity', verbose_name='nucleic acid purity')),
                ('nuc_acid_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formz.NucleicAcidRisk', verbose_name='nucleic acid risk potential')),
            ],
            options={
                'verbose_name': 'base element',
                'verbose_name_plural': 'base elements',
            },
        ),
        migrations.CreateModel(
            name='ZkbsPlasmid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('source', models.CharField(max_length=255, null=True, verbose_name='source')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'ZKBS plasmid',
                'verbose_name_plural': 'ZKBS plasmids',
            },
        ),
        migrations.AlterModelOptions(
            name='formzproject',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
    ]
