# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0003_auto_20190416_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='zkbsplasmid',
            name='purpose',
            field=models.CharField(max_length=255, null=True, verbose_name='purpose'),
        ),
    ]
