# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0004_zkbsplasmid_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormZHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(help_text='Name des Betreibers', max_length=255, null=True, verbose_name='operator')),
                ('address', models.TextField(help_text='Anschrift der gentechnischen Anlage', null=True, verbose_name='address of bioengineering facility')),
                ('name_biosafety_officer', models.CharField(help_text='Name des Beauftragten für die Biologische Sicherheit', max_length=255, null=True, verbose_name='name of the biosafety officer')),
                ('s1_approval_file_num', models.CharField(max_length=255, null=True, verbose_name='file number for S1 approval')),
                ('s1_approval_date', models.DateField(null=True, verbose_name='S1 approval date')),
                ('s2_approval_file_num', models.CharField(max_length=255, null=True, verbose_name='file number for S2 approval')),
                ('s2_approval_date', models.DateField(null=True, verbose_name='S2 approval date')),
            ],
            options={
                'verbose_name_plural': 'headers',
                'verbose_name': 'header',
            },
        ),
    ]
