# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0006_auto_20190416_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzheader',
            name='s1_approval_file_num',
            field=models.CharField(help_text='e.g. 21-29,8 B 56.01; TgbNr.: 8/29,0/11/36', max_length=255, null=True, verbose_name='file number for S1 approval'),
        ),
        migrations.AlterField(
            model_name='formzheader',
            name='s2_approval_file_num',
            field=models.CharField(help_text='e.g. 29,8 B 56.02:21; TgbNr.: 8/29,0/13/46', max_length=255, null=True, verbose_name='file number for S2 approval'),
        ),
    ]
