# Generated by Django 2.0.13 on 2019-04-17 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0007_auto_20190416_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzbaseelement',
            name='nuc_acid_purity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formz.NucleicAcidPurity', verbose_name='nucleic acid purity'),
        ),
        migrations.AlterField(
            model_name='formzbaseelement',
            name='nuc_acid_risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formz.NucleicAcidRisk', verbose_name='nucleic acid risk potential'),
        ),
    ]
