# Generated by Django 2.1.8 on 2019-05-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0009_auto_20190524_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzbaseelement',
            name='donor_organism',
            field=models.CharField(blank=True, max_length=255, verbose_name='donor organism'),
        ),
        migrations.AlterField(
            model_name='formzbaseelement',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='formzbaseelement',
            name='nuc_acid_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='nucleic acid type'),
        ),
        migrations.AlterField(
            model_name='formzheader',
            name='address',
            field=models.TextField(help_text='Anschrift der gentechnischen Anlage', verbose_name='address of bioengineering facility'),
        ),
        migrations.AlterField(
            model_name='formzheader',
            name='name_biosafety_officer',
            field=models.CharField(help_text='Name des Beauftragten für die Biologische Sicherheit', max_length=255, verbose_name='name of the biosafety officer'),
        ),
        migrations.AlterField(
            model_name='formzheader',
            name='operator',
            field=models.CharField(help_text='Name des Betreibers', max_length=255, verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='formzheader',
            name='s1_approval_file_num',
            field=models.CharField(help_text='e.g. 21-29,8 B 56.01; TgbNr.: 8/29,0/11/36', max_length=255, verbose_name='file number for S1 approval'),
        ),
        migrations.AlterField(
            model_name='formzheader',
            name='s2_approval_file_num',
            field=models.CharField(help_text='e.g. 29,8 B 56.02:21; TgbNr.: 8/29,0/13/46', max_length=255, verbose_name='file number for S2 approval'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='description',
            field=models.TextField(blank=True, help_text='Techniques, organisms, plasmids, etc.', verbose_name='Description of stratagy/performance'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='donor_organims',
            field=models.CharField(blank=True, help_text='Used organisms, their risk group and safety-relevant properties', max_length=255, verbose_name='donor organisms'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='generated_gmo',
            field=models.TextField(blank=True, help_text='Include risk groups and safety-relevant properties', verbose_name='generated GMOs'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='hazard_activity',
            field=models.TextField(blank=True, verbose_name='hazard-relevant characteristics of activity'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='hazards_employee',
            field=models.TextField(blank=True, verbose_name='severity and likelihood of hazards to employees and/or the environment'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='objectives',
            field=models.CharField(blank=True, max_length=255, verbose_name='objectives of strategy'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='potential_risk_nuc_acid',
            field=models.TextField(blank=True, help_text='Include safety-relevant properties', verbose_name='potential risks of transferred nucleic acids'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='project_leader',
            field=models.CharField(max_length=255, verbose_name='project leader'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='recipient_organisms',
            field=models.CharField(blank=True, help_text='Include risk groups and safety-relevant properties', max_length=255, verbose_name='recipient organisms'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='title',
            field=models.CharField(max_length=191, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='vectors',
            field=models.TextField(blank=True, help_text='Include safety-relevant properties', verbose_name='Vectors'),
        ),
        migrations.AlterField(
            model_name='gentechmethod',
            name='english_name',
            field=models.CharField(max_length=255, verbose_name='English name'),
        ),
        migrations.AlterField(
            model_name='gentechmethod',
            name='german_name',
            field=models.CharField(max_length=255, verbose_name='German name'),
        ),
        migrations.AlterField(
            model_name='nucleicacidpurity',
            name='english_name',
            field=models.CharField(max_length=255, verbose_name='English name'),
        ),
        migrations.AlterField(
            model_name='nucleicacidpurity',
            name='german_name',
            field=models.CharField(max_length=255, verbose_name='German name'),
        ),
        migrations.AlterField(
            model_name='nucleicacidrisk',
            name='english_name',
            field=models.CharField(max_length=255, verbose_name='English name'),
        ),
        migrations.AlterField(
            model_name='nucleicacidrisk',
            name='german_name',
            field=models.CharField(max_length=255, verbose_name='German name'),
        ),
        migrations.AlterField(
            model_name='zkbsplasmid',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='zkbsplasmid',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='zkbsplasmid',
            name='purpose',
            field=models.CharField(max_length=255, verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='zkbsplasmid',
            name='source',
            field=models.CharField(max_length=255, verbose_name='source'),
        ),
    ]
