# Generated by Django 2.1.8 on 2019-07-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0010_auto_20190524_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzbaseelement',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='name'),
        ),
    ]
