# Generated by Django 2.1.8 on 2019-07-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0012_formzbaseelement_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formzbaseelement',
            name='nuc_acid_type',
        ),
    ]
