# Generated by Django 2.1.8 on 2019-07-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0013_remove_formzbaseelement_nuc_acid_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formzbaseelement',
            options={'ordering': ['name'], 'verbose_name': 'base element', 'verbose_name_plural': 'base elements'},
        ),
        migrations.AlterModelOptions(
            name='formzproject',
            options={'ordering': ['id'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='gentechmethod',
            options={'ordering': ['english_name'], 'verbose_name': 'genTech method', 'verbose_name_plural': 'genTech methods'},
        ),
        migrations.AlterModelOptions(
            name='nucleicacidpurity',
            options={'ordering': ['english_name'], 'verbose_name': 'nuclei acid purity', 'verbose_name_plural': 'nuclei acid purities'},
        ),
        migrations.AlterModelOptions(
            name='nucleicacidrisk',
            options={'ordering': ['english_name'], 'verbose_name': 'nuclei acid risk potential', 'verbose_name_plural': 'nuclei acid risk potentials'},
        ),
        migrations.AlterModelOptions(
            name='zkbsplasmid',
            options={'ordering': ['name'], 'verbose_name': 'ZKBS plasmid', 'verbose_name_plural': 'ZKBS plasmids'},
        ),
    ]
