# Generated by Django 2.1.8 on 2019-07-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0015_formzbaseelement_common_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZkbsCellLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('synonym', models.CharField(max_length=255, verbose_name='synonym')),
                ('organism', models.CharField(max_length=255, verbose_name='organism')),
                ('risk_potential', models.CharField(max_length=255, verbose_name='risk potential')),
                ('origin', models.CharField(max_length=255, verbose_name='origin')),
                ('virus', models.CharField(max_length=255, verbose_name='virus')),
                ('genetically_modified', models.BooleanField(blank=True, verbose_name='genetically modified?')),
            ],
            options={
                'verbose_name': 'ZKBS cell line',
                'verbose_name_plural': 'ZKBS cell lines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ZkbsOncogene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('synonym', models.CharField(max_length=255, verbose_name='synonym')),
                ('species', models.CharField(max_length=255, verbose_name='species')),
                ('risk_potential', models.CharField(max_length=255, verbose_name='risk potential')),
                ('reference', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'ZKBS oncogene',
                'verbose_name_plural': 'ZKBS oncogenes',
                'ordering': ['name'],
            },
        ),
    ]
