# Generated by Django 2.1.8 on 2019-07-19 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0016_zkbscellline_zkbsoncogene'),
    ]

    operations = [
        migrations.AddField(
            model_name='formzbaseelement',
            name='zkbs_oncogene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formz.ZkbsOncogene', verbose_name='ZKBS database oncogene'),
        ),
    ]
