# Generated by Django 2.1.8 on 2019-07-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0020_auto_20190719_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formzstoragelocation',
            old_name='collection_models',
            new_name='collection_model',
        ),
    ]
