# Generated by Django 2.1.8 on 2019-07-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0021_auto_20190719_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zkbscellline',
            name='synonym',
            field=models.CharField(blank=True, max_length=255, verbose_name='synonym'),
        ),
    ]
