# Generated by Django 2.1.8 on 2019-07-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0022_auto_20190719_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='zkbsoncogene',
            name='additional_measures',
            field=models.BooleanField(blank=True, default=False, verbose_name='additional measures?'),
            preserve_default=False,
        ),
    ]
