# Generated by Django 2.1.8 on 2019-07-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0023_zkbsoncogene_additional_measures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzproject',
            name='beginning_work_date',
            field=models.DateField(help_text='Beginn der Arbeiten', null=True, verbose_name='beginning of work'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='description',
            field=models.TextField(blank=True, help_text='Techniques, organisms, plasmids, etc. Beschreibung der Durchführung', verbose_name='Description of strategy/performance'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='donor_organims',
            field=models.CharField(blank=True, help_text='Used organisms, their risk group and safety-relevant properties. Verwendete Spenderorganismen', max_length=255, verbose_name='donor organisms'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='end_work_date',
            field=models.DateField(blank=True, help_text='Ende der Arbeiten', null=True, verbose_name='end of work'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='generated_gmo',
            field=models.TextField(blank=True, help_text='Include risk groups and safety-relevant properties. Erzeugte GVO', verbose_name='generated GMOs'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='hazard_activity',
            field=models.TextField(blank=True, help_text='Gefährdungsrelevante Merkmale der Tätigkeit', verbose_name='hazard-relevant characteristics of activity'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='hazards_employee',
            field=models.TextField(blank=True, help_text='Schwere und Wahrscheinlichkeit einer Gefährdung der Mitarbeiter und/oder der Umwelt', verbose_name='severity and likelihood of hazards to employees and/or the environment'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='objectives',
            field=models.CharField(blank=True, help_text='Zielsetzung', max_length=255, verbose_name='objectives of strategy'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='potential_risk_nuc_acid',
            field=models.TextField(blank=True, help_text='Include safety-relevant properties. Gefährdungspotentiale der übertragenen Nukleinsäuren', verbose_name='potential risks of transferred nucleic acids'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='project_leader',
            field=models.CharField(help_text='Projektleiter', max_length=255, verbose_name='project leader'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='recipient_organisms',
            field=models.CharField(blank=True, help_text='Include risk groups and safety-relevant properties. Verwendete Empfängerorganismen', max_length=255, verbose_name='recipient organisms'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='safety_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], help_text='Sicherheitsstufe', null=True, verbose_name='safety level'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='title',
            field=models.CharField(help_text='titel', max_length=191, verbose_name='title'),
        ),
    ]
