# Generated by Django 2.1.8 on 2019-07-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0024_auto_20190722_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzproject',
            name='end_work_date',
            field=models.DateField(blank=True, help_text='<i>Ende der Arbeiten</i>', null=True, verbose_name='end of work'),
        ),
    ]
