# Generated by Django 2.1.8 on 2019-07-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0027_auto_20190722_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzproject',
            name='title',
            field=models.CharField(help_text='<i>Titel</i>', max_length=191, verbose_name='title'),
        ),
    ]
