# Generated by Django 2.1.8 on 2019-07-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0029_auto_20190723_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formzbaseelement',
            name='extra_labels',
        ),
    ]
