# Generated by Django 2.1.8 on 2019-07-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0030_remove_formzbaseelement_extra_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzbaseelementextralabel',
            name='label',
            field=models.CharField(blank=True, max_length=255, verbose_name='label'),
        ),
    ]
