# Generated by Django 2.1.8 on 2019-07-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0031_auto_20190723_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formzbaseelementextralabel',
            name='formz_base_element',
        ),
        migrations.DeleteModel(
            name='FormZBaseElementExtraLabel',
        ),
    ]
