# Generated by Django 2.1.8 on 2019-07-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0032_auto_20190723_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormZBaseElementExtraLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, unique=True, verbose_name='label')),
                ('formz_base_element', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formz.FormZBaseElement')),
            ],
            options={
                'verbose_name': 'base element extra label',
                'verbose_name_plural': 'base element extra labels',
                'ordering': ['label'],
            },
        ),
    ]
