# Generated by Django 2.1.8 on 2019-07-23 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0033_formzbaseelementextralabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzbaseelementextralabel',
            name='formz_base_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extra_label', to='formz.FormZBaseElement'),
        ),
    ]
