# Generated by Django 2.1.8 on 2019-07-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0034_auto_20190723_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzbaseelement',
            name='zkbs_oncogene',
            field=models.ForeignKey(blank=True, help_text='<a href="/formz/zkbsoncogene/" target="_blank">View</a>', null=True, on_delete=django.db.models.deletion.PROTECT, to='formz.ZkbsOncogene', verbose_name='ZKBS database oncogene'),
        ),
    ]
