# Generated by Django 2.1.8 on 2019-07-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0035_auto_20190723_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzbaseelement',
            name='donor_organism',
            field=models.CharField(blank=True, help_text='As species, e.g. Homo sapiens', max_length=255, verbose_name='donor organism'),
        ),
    ]
