# Generated by Django 2.1.8 on 2019-07-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0036_auto_20190726_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzbaseelement',
            name='name',
            field=models.CharField(blank=True, help_text='Must be identical (CASE-SENSITIVE!) to a feature name in a plasmid map for auto-detection to work', max_length=255, unique=True, verbose_name='name'),
        ),
    ]
