# Generated by Django 2.1.8 on 2019-07-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0037_auto_20190726_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='formzstoragelocation',
            name='species_name',
            field=models.CharField(default='Lalala', max_length=255, verbose_name='species name'),
            preserve_default=False,
        ),
    ]
