# Generated by Django 2.1.8 on 2019-07-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0038_formzstoragelocation_species_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzstoragelocation',
            name='species_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='species name'),
        ),
    ]
