# Generated by Django 2.1.8 on 2019-07-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0039_auto_20190729_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='formzproject',
            name='short_title',
            field=models.CharField(default='alalala', max_length=255, verbose_name='short title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='title',
            field=models.CharField(help_text='<i>Titel</i>', max_length=255, verbose_name='title'),
        ),
    ]
