# Generated by Django 2.1.8 on 2019-07-31 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0040_auto_20190729_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzstoragelocation',
            name='collection_model',
            field=models.OneToOneField(help_text='Strain, plasmids, cell lines, etc.', null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='collection'),
        ),
        migrations.AlterField(
            model_name='formzstoragelocation',
            name='species_name',
            field=models.CharField(blank=True, help_text='Full species name, e.g. Homo sapiens', max_length=255, verbose_name='species name'),
        ),
        migrations.AlterField(
            model_name='formzstoragelocation',
            name='storage_location',
            field=models.CharField(help_text='Room where the collection is stored', max_length=255, verbose_name='storage location'),
        ),
    ]
