# Generated by Django 2.1.8 on 2019-07-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0041_auto_20190731_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='formzproject',
            name='short_title_english',
            field=models.CharField(default='lallal', max_length=255, verbose_name='English short title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='short_title',
            field=models.CharField(help_text='<i>Kurzer Titel</i>', max_length=255, verbose_name='short title'),
        ),
    ]
