# Generated by Django 2.1.8 on 2019-08-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0042_auto_20190731_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzbaseelementextralabel',
            name='label',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='alias'),
        ),
    ]
