# Generated by Django 2.1.8 on 2019-08-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0043_auto_20190801_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formzbaseelementextralabel',
            options={'ordering': ['label'], 'verbose_name': 'base element alias', 'verbose_name_plural': 'base element aliases'},
        ),
    ]
