# Generated by Django 2.1.8 on 2019-08-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0044_auto_20190801_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzbaseelement',
            name='name',
            field=models.CharField(blank=True, help_text='Must be identical (CASE-SENSITIVE!) to a feature name in a plasmid map for auto-detection to work. If you want to associate additional names to an element, add them as aliases below', max_length=255, unique=True, verbose_name='name'),
        ),
    ]
