# Generated by Django 2.1.8 on 2019-08-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0045_auto_20190801_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formzbaseelement',
            options={'ordering': ['name'], 'verbose_name': 'sequence element', 'verbose_name_plural': 'sequence elements'},
        ),
    ]
