# Generated by Django 2.1.8 on 2019-08-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0046_auto_20190806_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzbaseelement',
            name='donor_organism',
            field=models.CharField(blank=True, help_text='As species, e.g. Homo sapiens; use none if no organism applies', max_length=255, verbose_name='donor organism'),
        ),
    ]
