# Generated by Django 2.1.8 on 2019-09-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0048_formzproject_parent_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzbaseelementextralabel',
            name='label',
            field=models.CharField(blank=True, max_length=255, verbose_name='alias'),
        ),
    ]
