# Generated by Django 2.1.8 on 2019-09-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0049_auto_20190905_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='formzstoragelocation',
            name='species_risk_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], null=True, verbose_name='species risk group'),
        ),
    ]
