# Generated by Django 2.1.8 on 2019-09-14 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formz', '0050_formzstoragelocation_species_risk_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormZUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_work_date', models.DateField(blank=True, null=True, verbose_name='start of work')),
                ('end_work_date', models.DateField(blank=True, null=True, verbose_name='end of work')),
                ('formz_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formz.FormZProject', verbose_name='formZ project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='formzproject',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='formz_project_users', through='formz.FormZUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
