# Generated by Django 2.1.8 on 2019-09-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0052_auto_20190914_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzusers',
            name='beginning_work_date',
            field=models.DateField(blank=True, null=True, verbose_name='beginning of work'),
        ),
    ]
