# Generated by Django 2.1.8 on 2019-09-14 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0054_auto_20190914_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzproject',
            name='project_leader',
            field=models.ManyToManyField(help_text='<i>Projektleiter</i>', to=settings.AUTH_USER_MODEL, verbose_name='project leaders'),
        ),
    ]
