# Generated by Django 2.1.8 on 2019-09-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0056_auto_20190914_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzbaseelement',
            name='donor_organism_risk',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True, verbose_name='risk group'),
        ),
    ]
