# Generated by Django 2.1.8 on 2019-09-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0057_auto_20190914_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzbaseelement',
            name='common_feature',
            field=models.BooleanField(default=False, help_text='e.g. an antibiotic resistance marker or a commonly used promoter', verbose_name='is this a common plasmid feature?'),
        ),
        migrations.AlterField(
            model_name='formzbaseelement',
            name='donor_organism',
            field=models.CharField(help_text='As species, e.g. Homo sapiens; use none if no organism applies', max_length=255, verbose_name='donor organism'),
        ),
        migrations.AlterField(
            model_name='formzbaseelement',
            name='donor_organism_risk',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], null=True, verbose_name='Donor organism risk group'),
        ),
        migrations.AlterField(
            model_name='formzbaseelement',
            name='name',
            field=models.CharField(help_text='Must be identical (CASE-SENSITIVE!) to a feature name in a plasmid map for auto-detection to work. If you want to associate additional names to an element, add them as aliases below', max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='formzbaseelement',
            name='nuc_acid_purity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='formz.NucleicAcidPurity', verbose_name='nucleic acid purity'),
        ),
        migrations.AlterField(
            model_name='formzbaseelement',
            name='nuc_acid_risk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='formz.NucleicAcidRisk', verbose_name='nucleic acid risk potential'),
        ),
    ]
