# Generated by Django 2.1.8 on 2019-10-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0061_auto_20191003_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formzbaseelement',
            name='donor_organism',
        ),
    ]
