# Generated by Django 2.1.8 on 2019-10-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0063_auto_20191003_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzbaseelement',
            name='donor_organism',
            field=models.ManyToManyField(to='formz.Species', verbose_name='donor organism'),
        ),
    ]
