# Generated by Django 2.1.8 on 2019-10-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0064_auto_20191003_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzbaseelement',
            name='donor_organism',
            field=models.ManyToManyField(help_text='Choose none, for artificial elements', to='formz.Species', verbose_name='donor organism'),
        ),
    ]
