# Generated by Django 2.1.8 on 2019-10-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0065_auto_20191003_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formzstoragelocation',
            name='species_name',
        ),
    ]
