# Generated by Django 2.1.8 on 2019-10-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0067_formzstoragelocation_species_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='name_for_search',
            field=models.CharField(default='la', max_length=255),
            preserve_default=False,
        ),
    ]
