# Generated by Django 2.1.8 on 2019-10-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0068_species_name_for_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='risk_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], null=True, verbose_name='risk group'),
        ),
    ]
