# Generated by Django 2.1.8 on 2019-10-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0069_species_risk_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formzbaseelement',
            name='donor_organism_risk',
        ),
        migrations.AlterField(
            model_name='species',
            name='name_for_search',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
