# Generated by Django 2.1.8 on 2019-10-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0071_auto_20191004_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='name_for_search',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
