# Generated by Django 2.1.8 on 2019-10-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0072_auto_20191004_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='risk_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name='risk group'),
        ),
    ]
