# Generated by Django 2.1.13 on 2019-11-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0073_auto_20191004_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='formzbaseelement',
            name='displayed_name',
            field=models.CharField(blank=True, help_text="If present, the name displayed in the rendered FormZ form, instead of 'Name' above. This is useful for those elements whose names, due to uniqueness contrains, include species information, e.g. 'Hs PCNA', which would be more appropriate to display simply as 'PCNA' in the rendered form", max_length=255, verbose_name='displayed name'),
        ),
    ]
