# Generated by Django 2.1.13 on 2019-11-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0074_formzbaseelement_displayed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzbaseelementextralabel',
            name='label',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='alias'),
        ),
    ]
