# Generated by Django 3.2.6 on 2021-10-20 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formz', '0078_auto_20191117_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formzproject',
            name='project_leader',
            field=models.ManyToManyField(help_text='<i>Projektleiter</i>', to=settings.AUTH_USER_MODEL, verbose_name='project leaders'),
        ),
    ]
