# Generated by Django 3.2.15 on 2023-01-04 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formz', '0081_alter_formzproject_project_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='formzproject',
            name='deputy_project_leader',
            field=models.ManyToManyField(blank=True, help_text='<i>Stellvertretende Projektleiter</i>', related_name='formz_deputy_project_leader', to=settings.AUTH_USER_MODEL, verbose_name='deputy project leaders'),
        ),
        migrations.AddField(
            model_name='formzproject',
            name='genetic_work_classification',
            field=models.CharField(blank=True, help_text='<i>Einstufung der gentechnischen Arbeiten</i>', max_length=255, verbose_name='classification of genetic work'),
        ),
        migrations.AlterField(
            model_name='formzproject',
            name='project_leader',
            field=models.ManyToManyField(help_text='<i>Projektleiter</i>', related_name='formz_project_leader', to=settings.AUTH_USER_MODEL, verbose_name='project leaders'),
        ),
    ]
