# Generated by Django 4.2.17 on 2025-03-10 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("collection", "0245_alter_historicalwormstrain_at_cgc_and_more"),
        ("formz", "0082_auto_20230104_1520"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FormZHeader",
            new_name="Header",
        ),
        migrations.RenameModel(
            old_name="FormZUsers",
            new_name="ProjectUsers",
        ),
        migrations.RenameModel(
            old_name="FormZBaseElement",
            new_name="SequenceElement",
        ),
        migrations.RenameModel(
            old_name="FormZBaseElementExtraLabel",
            new_name="SequenceElementAlias",
        ),
        migrations.RenameModel(
            old_name="FormZStorageLocation",
            new_name="StorageLocation",
        ),
        migrations.AlterModelOptions(
            name="sequenceelementalias",
            options={
                "ordering": ["label"],
                "verbose_name": "sequence element alias",
                "verbose_name_plural": "sequence element aliases",
            },
        ),
        migrations.RenameModel(
            old_name="FormZProject",
            new_name="Project",
        ),
    ]
