# Generated by Django 4.2.17 on 2025-03-10 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("formz", "0083_rename_formzheader_header_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sequenceelementalias",
            old_name="formz_base_element",
            new_name="sequence_element",
        ),
    ]
