# Generated by Django 4.2.17 on 2025-03-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "formz",
            "0084_rename_formz_base_element_sequenceelementalias_sequence_element",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequenceelementalias",
            name="sequence_element",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alias",
                to="formz.sequenceelement",
            ),
        ),
    ]
