# Generated by Django 4.2.17 on 2025-03-11 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "collection",
            "0248_rename_history_sequence_elements_cellline_history_sequence_features_and_more",
        ),
        ("formz", "0085_alter_sequenceelementalias_sequence_element"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SequenceElement",
            new_name="SequenceFeature",
        ),
        migrations.RenameModel(
            old_name="SequenceElementAlias",
            new_name="SequenceFeatureAlias",
        ),
        migrations.AlterModelOptions(
            name="sequencefeature",
            options={
                "ordering": ["name"],
                "verbose_name": "sequence feature",
                "verbose_name_plural": "sequence features",
            },
        ),
        migrations.RenameField(
            model_name="sequencefeaturealias",
            old_name="sequence_element",
            new_name="sequence_feature",
        ),
    ]
