# Generated by Django 4.2.17 on 2025-03-11 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("formz", "0086_rename_sequenceelement_sequencefeature_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sequencefeaturealias",
            options={
                "ordering": ["label"],
                "verbose_name": "sequence feature alias",
                "verbose_name_plural": "sequence feature aliases",
            },
        ),
    ]
