# Generated by Django 4.2.17 on 2025-03-11 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("formz", "0087_alter_sequencefeaturealias_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storagelocation",
            old_name="species_name",
            new_name="species",
        ),
        migrations.AlterField(
            model_name="storagelocation",
            name="species",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="formz.species",
                verbose_name="species",
            ),
        ),
    ]
