# Generated by Django 4.2.17 on 2025-03-14 07:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("formz", "0088_rename_species_name_storagelocation_species"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectUsers",
            new_name="ProjectUser",
        ),
    ]
