# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0005_auto_20180705_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='parental_line',
            field=models.CharField(blank=True, max_length=255, verbose_name='Parental cell line'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='parental_line',
            field=models.CharField(blank=True, max_length=255, verbose_name='Parental cell line'),
        ),
    ]
