# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0008_auto_20180705_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmammalianlinedoc',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalmammalianlinedoc',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='mammalianlinedoc',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mammalianlinedoc',
            name='created_date_time',
        ),
        migrations.RemoveField(
            model_name='mammalianlinedoc',
            name='date_of_test',
        ),
        migrations.RemoveField(
            model_name='mammalianlinedoc',
            name='last_changed_date_time',
        ),
        migrations.RemoveField(
            model_name='mammalianlinedoc',
            name='typ_e',
        ),
        migrations.DeleteModel(
            name='HistoricalMammalianLineDoc',
        ),
    ]
