# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0013_auto_20180705_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MammalianLineDoc',
        ),
    ]
