# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 12:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection_management', '0020_auto_20180705_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMammalianLineDoc',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='File name')),
                ('typ_e', models.CharField(choices=[['virus', 'Virus test'], ['mycoplasma', 'Mycoplasma test'], ['fingerprint', 'Fingerprinting'], ['other', 'Other']], max_length=255, verbose_name='Doc Type')),
                ('date_of_test', models.DateTimeField(verbose_name='Date of test')),
                ('created_date_time', models.DateTimeField(blank=True, editable=False, verbose_name='Created')),
                ('last_changed_date_time', models.DateTimeField(blank=True, editable=False, verbose_name='Last Changed')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical mammalian cell line document',
            },
        ),
        migrations.CreateModel(
            name='MammalianLineDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(upload_to='temp/', verbose_name='File name')),
                ('typ_e', models.CharField(choices=[['virus', 'Virus test'], ['mycoplasma', 'Mycoplasma test'], ['fingerprint', 'Fingerprinting'], ['other', 'Other']], max_length=255, verbose_name='Doc Type')),
                ('date_of_test', models.DateTimeField(verbose_name='Date of test')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_changed_date_time', models.DateTimeField(auto_now=True, verbose_name='Last Changed')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mammalian cell line document',
            },
        ),
        migrations.AddField(
            model_name='historicalmammalianline',
            name='document',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collection_management.MammalianLineDoc'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection_management.MammalianLineDoc', verbose_name='Document (max. 2 MB)'),
        ),
    ]
