# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0025_auto_20180705_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmammalianlinedoc',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mammalianlinedoc',
            name='created_by',
        ),
    ]
