# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0037_auto_20180706_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='parental_line',
            field=models.CharField(max_length=255, verbose_name='Parental cell line'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='parental_line',
            field=models.CharField(max_length=255, verbose_name='Parental cell line'),
        ),
    ]
