# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-03 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0038_auto_20180710_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalscpombestrain',
            old_name='genotype',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='scpombestrain',
            old_name='genotype',
            new_name='name',
        ),
    ]
