# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-03 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0039_auto_20180803_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalhuplasmid',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical HU plasmid'},
        ),
        migrations.AlterModelOptions(
            name='huplasmid',
            options={'verbose_name': 'HU plasmid', 'verbose_name_plural': 'HU plasmids'},
        ),
    ]
