# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-12 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0042_auto_20180812_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecolistrain',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='Record Creation Approval'),
        ),
        migrations.AddField(
            model_name='ecolistrain',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='Record Change Approval'),
        ),
        migrations.AddField(
            model_name='historicalecolistrain',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='Record Creation Approval'),
        ),
        migrations.AddField(
            model_name='historicalecolistrain',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='Record Change Approval'),
        ),
        migrations.AddField(
            model_name='historicalhuplasmid',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='Record Creation Approval'),
        ),
        migrations.AddField(
            model_name='historicalhuplasmid',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='Record Change Approval'),
        ),
        migrations.AddField(
            model_name='historicalmammalianline',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='Record Creation Approval'),
        ),
        migrations.AddField(
            model_name='historicalmammalianline',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='Record Change Approval'),
        ),
        migrations.AddField(
            model_name='historicalnzplasmid',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='Record Creation Approval'),
        ),
        migrations.AddField(
            model_name='historicalnzplasmid',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='Record Change Approval'),
        ),
        migrations.AddField(
            model_name='historicaloligo',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='Record Creation Approval'),
        ),
        migrations.AddField(
            model_name='historicaloligo',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='Record Change Approval'),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='Record Creation Approval'),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='Record Change Approval'),
        ),
        migrations.AddField(
            model_name='huplasmid',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='Record Creation Approval'),
        ),
        migrations.AddField(
            model_name='huplasmid',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='Record Change Approval'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='Record Creation Approval'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='Record Change Approval'),
        ),
        migrations.AddField(
            model_name='nzplasmid',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='Record Creation Approval'),
        ),
        migrations.AddField(
            model_name='nzplasmid',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='Record Change Approval'),
        ),
        migrations.AddField(
            model_name='oligo',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='Record Creation Approval'),
        ),
        migrations.AddField(
            model_name='oligo',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='Record Change Approval'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='Record Creation Approval'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='Record Change Approval'),
        ),
    ]
