# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0044_auto_20181116_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmammalianlinedoc',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mammalianlinedoc',
            name='created_by',
        ),
    ]
