# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0045_auto_20181116_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antibody',
            name='arche_noah_choice',
        ),
        migrations.RemoveField(
            model_name='historicalantibody',
            name='arche_noah_choice',
        ),
    ]
