# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0051_auto_20190409_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huplasmid',
            name='plasmid_map_png',
            field=models.ImageField(blank=True, upload_to='collection_management/huplasmid/png/', verbose_name='Plasmid image'),
        ),
    ]
