# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0052_auto_20190409_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalhuplasmid',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical plasmid'},
        ),
        migrations.AlterModelOptions(
            name='huplasmid',
            options={'verbose_name': 'plasmid', 'verbose_name_plural': 'plasmids'},
        ),
        migrations.AddField(
            model_name='historicalhuplasmid',
            name='plasmid_map_gbk',
            field=models.TextField(blank=True, max_length=100, verbose_name='Plasmid map (.gbk)'),
        ),
        migrations.AddField(
            model_name='huplasmid',
            name='plasmid_map_gbk',
            field=models.FileField(blank=True, upload_to='collection_management/huplasmid/gb/', verbose_name='Plasmid map (.gbk)'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='plasmid_map',
            field=models.TextField(blank=True, max_length=100, verbose_name='Plasmid map (.dna, max. 2 MB)'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='plasmid_map',
            field=models.FileField(blank=True, upload_to='collection_management/huplasmid/', verbose_name='Plasmid map (.dna, max. 2 MB)'),
        ),
    ]
