# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0053_auto_20190410_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='plasmid_map',
            field=models.TextField(blank=True, max_length=100, verbose_name='Plasmid map (max. 2 MB)'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='plasmid_map',
            field=models.FileField(blank=True, upload_to='collection_management/huplasmid/', verbose_name='Plasmid map (max. 2 MB)'),
        ),
    ]
