# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 15:11
from __future__ import unicode_literals

from django.db import migrations, models, connection


def alter_table(apps, schema_editor):
    query ="ALTER TABLE collection_management_plasmid ADD UNIQUE (name);"
    cursor = connection.cursor()
    cursor.execute(query)
    cursor.close()

class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0055_auto_20190411_1711'),
    ]

    operations = [migrations.RunPython(alter_table),]
