# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0056_auto_20190411_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='mating_type',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('alpha', 'alpha'), ('unknown', 'unknown'), ('a/a', 'a/a'), ('alpha/alpha', 'alpha/alpha'), ('a/alpha', 'a/alpha')], max_length=20, verbose_name='Mating Type'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='mating_type',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('alpha', 'alpha'), ('unknown', 'unknown'), ('a/a', 'a/a'), ('alpha/alpha', 'alpha/alpha'), ('a/alpha', 'a/alpha')], max_length=20, verbose_name='Mating Type'),
        ),
    ]
