# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0063_auto_20190412_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='description_comment',
            field=models.TextField(blank=True, help_text='max. 500 characters', max_length=500, verbose_name='description/comments'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='description_comment',
            field=models.TextField(blank=True, help_text='max. 500 characters', max_length=500, verbose_name='description/comments'),
        ),
    ]
