# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-14 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0066_mammalianlinedoc_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='description_comment',
            field=models.TextField(blank=True, verbose_name='description/comments'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='description_comment',
            field=models.TextField(blank=True, verbose_name='description/comments'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='description_comment',
            field=models.TextField(blank=True, verbose_name='description/comments'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='description_comment',
            field=models.TextField(blank=True, verbose_name='description/comments'),
        ),
    ]
