# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0003_auto_20190416_1748'),
        ('collection_management', '0068_auto_20190414_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhuplasmid',
            name='vector_known_zkbs',
            field=models.NullBooleanField(default=None, verbose_name='backbone in ZKBS database?'),
        ),
        migrations.AddField(
            model_name='historicalhuplasmid',
            name='vector_zkbs',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formz.ZkbsPlasmid'),
        ),
        migrations.AddField(
            model_name='huplasmid',
            name='formz_elements',
            field=models.ManyToManyField(to='formz.FormZBaseElement', verbose_name='formZ elements'),
        ),
        migrations.AddField(
            model_name='huplasmid',
            name='vector_known_zkbs',
            field=models.NullBooleanField(default=None, verbose_name='backbone in ZKBS database?'),
        ),
        migrations.AddField(
            model_name='huplasmid',
            name='vector_zkbs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formz.ZkbsPlasmid', verbose_name='ZKBS database vector'),
        ),
    ]
