# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0071_auto_20190416_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huplasmid',
            name='formz_elements',
            field=models.ManyToManyField(blank=True, to='formz.FormZBaseElement', verbose_name='Elements'),
        ),
    ]
