# Generated by Django 2.1.8 on 2019-04-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0076_auto_20190421_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='parental_strain',
            field=models.CharField(blank=True, help_text="Use only when the 'Parent 1' field does not apply", max_length=255, verbose_name='parental strain'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='parental_strain',
            field=models.CharField(blank=True, help_text="Use only when the 'Parent 1' field does not apply", max_length=255, verbose_name='parental strain'),
        ),
    ]
