# Generated by Django 2.1.8 on 2019-04-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0078_auto_20190423_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
