# Generated by Django 2.1.8 on 2019-04-24 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0081_mammalianline_integrated_plasmids'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='parent_1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collection_management.ScPombeStrain'),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='parent_2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collection_management.ScPombeStrain'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='cassette_plasmids',
            field=models.ManyToManyField(blank=True, help_text='Tagging and knock out plasmids', related_name='pom_cassette_pl', to='collection_management.HuPlasmid'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='integrated_plasmids',
            field=models.ManyToManyField(blank=True, related_name='pom_integrated_pl', to='collection_management.HuPlasmid'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='parent_1',
            field=models.ForeignKey(blank=True, help_text='Main parental strain', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pom_parent_strain_1', to='collection_management.ScPombeStrain', verbose_name='Parent 1'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='parent_2',
            field=models.ForeignKey(blank=True, help_text='Only for crosses', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pom_parent_strain_2', to='collection_management.ScPombeStrain', verbose_name='Parent 2'),
        ),
    ]
