# Generated by Django 2.1.8 on 2019-04-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0083_auto_20190425_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalhuplasmid',
            old_name='parent_vector',
            new_name='old_parent_vector',
        ),
        migrations.RenameField(
            model_name='huplasmid',
            old_name='parent_vector',
            new_name='old_parent_vector',
        ),
    ]
