# Generated by Django 2.1.8 on 2019-04-25 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0084_auto_20190425_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhuplasmid',
            name='parent_vector',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collection_management.HuPlasmid'),
        ),
        migrations.AddField(
            model_name='huplasmid',
            name='parent_vector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='par_vect', to='collection_management.HuPlasmid', verbose_name='parent vector'),
        ),
    ]
