# Generated by Django 2.1.8 on 2019-04-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0086_auto_20190425_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='old_parent_vector',
            field=models.CharField(blank=True, help_text='Use only when strictly necessary', max_length=255, verbose_name='orig. parent vector field'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='old_parent_vector',
            field=models.CharField(blank=True, help_text='Use only when strictly necessary', max_length=255, verbose_name='orig. parent vector field'),
        ),
    ]
