# Generated by Django 2.1.8 on 2019-05-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0091_auto_20190517_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacerevisiaestrainepisomalplasmid',
            name='present_in_stocked_strain',
            field=models.BooleanField(default=False, null=True, verbose_name='record creation approval'),
        ),
    ]
