# Generated by Django 2.1.8 on 2019-05-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0095_sacerevisiaestrainepisomalplasmid_form_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sacerevisiaestrainepisomalplasmid',
            old_name='form_project',
            new_name='formz_project',
        ),
    ]
