# Generated by Django 2.1.8 on 2019-05-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0097_auto_20190520_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacerevisiaestrainepisomalplasmid',
            name='created_date',
            field=models.DateField(null=True),
        ),
    ]
