# Generated by Django 2.1.8 on 2019-05-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0099_auto_20190520_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacerevisiaestrainepisomalplasmid',
            name='formz_project',
            field=models.ManyToManyField(blank=True, related_name='sc_epi_plasmid', to='formz.FormZProject'),
        ),
    ]
