# Generated by Django 2.1.8 on 2019-05-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0101_auto_20190520_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacerevisiaestrainepisomalplasmid',
            name='present_in_stocked_strain',
            field=models.BooleanField(default=False, null=True, verbose_name='Present in -80° C stock?'),
        ),
    ]
