# Generated by Django 2.1.8 on 2019-05-21 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0107_auto_20190521_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='construction_feature',
            field=models.TextField(blank=True, null=True, verbose_name='construction/features'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='name',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='old_parent_vector',
            field=models.CharField(blank=True, help_text='Use only when strictly necessary', max_length=255, null=True, verbose_name='orig. parent vector field'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='other_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='other name'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='plasmid_map',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='plasmid map (max. 2 MB)'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='plasmid_map_gbk',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='plasmid map (.gbk)'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='plasmid_map_png',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='plasmid image'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='selection',
            field=models.CharField(max_length=50, null=True, verbose_name='selection'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='us_e',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='use'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='construction_feature',
            field=models.TextField(blank=True, null=True, verbose_name='construction/features'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='formz_elements',
            field=models.ManyToManyField(blank=True, to='formz.FormZBaseElement', verbose_name='elements'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='old_parent_vector',
            field=models.CharField(blank=True, help_text='Use only when strictly necessary', max_length=255, null=True, verbose_name='orig. parent vector field'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='other_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='other name'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='parent_vector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plasmid_parent_vector', to='collection_management.HuPlasmid', verbose_name='parent vector'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='plasmid_map',
            field=models.FileField(blank=True, null=True, upload_to='collection_management/huplasmid/dna/', verbose_name='plasmid map (max. 2 MB)'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='plasmid_map_gbk',
            field=models.FileField(blank=True, null=True, upload_to='collection_management/huplasmid/gb/', verbose_name='plasmid map (.gbk)'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='plasmid_map_png',
            field=models.ImageField(blank=True, null=True, upload_to='collection_management/huplasmid/png/', verbose_name='plasmid image'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='selection',
            field=models.CharField(max_length=50, null=True, verbose_name='selection'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='us_e',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='use'),
        ),
    ]
