# Generated by Django 2.1.8 on 2019-05-21 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0109_auto_20190521_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='auxotrophic_marker',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='auxotrophic markers'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='box_number',
            field=models.SmallIntegerField(null=True, verbose_name='box number'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='mating_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='mating type'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='name',
            field=models.TextField(null=True, verbose_name='genotype'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='parental_strain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='parental strains'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='phenotype',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='phenotype'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='auxotrophic_marker',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='auxotrophic markers'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='box_number',
            field=models.SmallIntegerField(null=True, verbose_name='box number'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='cassette_plasmids',
            field=models.ManyToManyField(blank=True, help_text='Tagging and knock out plasmids', null=True, related_name='pombe_cassette_plasmids', to='collection_management.HuPlasmid'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='integrated_plasmids',
            field=models.ManyToManyField(blank=True, null=True, related_name='pombe_integrated_plasmids', to='collection_management.HuPlasmid'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='mating_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='mating type'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='name',
            field=models.TextField(null=True, verbose_name='genotype'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='parent_1',
            field=models.ForeignKey(blank=True, help_text='Main parental strain', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pombe_parent_1', to='collection_management.ScPombeStrain', verbose_name='Parent 1'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='parent_2',
            field=models.ForeignKey(blank=True, help_text='Only for crosses', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pombe_parent_2', to='collection_management.ScPombeStrain', verbose_name='Parent 2'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='parental_strain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='parental strains'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='phenotype',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='phenotype'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='received from'),
        ),
    ]
