# Generated by Django 2.1.8 on 2019-05-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0112_auto_20190521_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnzplasmid',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalnzplasmid',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='nzplasmid',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='HistoricalNzPlasmid',
        ),
        migrations.DeleteModel(
            name='NzPlasmid',
        ),
    ]
