# Generated by Django 2.1.8 on 2019-05-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0116_auto_20190522_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='background',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='background',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='background'),
        ),
    ]
