# Generated by Django 2.1.8 on 2019-05-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0119_auto_20190522_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='construction_feature',
            field=models.TextField(blank=True, default='', verbose_name='construction/features'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='map',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='plasmid map (max. 2 MB)'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='map_gbk',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='plasmid map (.gbk)'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='map_png',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='plasmid image'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='note',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='old_parent_vector',
            field=models.CharField(blank=True, default='', help_text='Use only when strictly necessary', max_length=255, verbose_name='orig. parent vector field'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='other_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='other name'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='received_from',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='selection',
            field=models.CharField(default='', max_length=50, verbose_name='selection'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='us_e',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='use'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='construction_feature',
            field=models.TextField(blank=True, default='', verbose_name='construction/features'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='map',
            field=models.FileField(blank=True, default='', upload_to='collection_management/huplasmid/dna/', verbose_name='plasmid map (max. 2 MB)'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='map_gbk',
            field=models.FileField(blank=True, default='', upload_to='collection_management/huplasmid/gb/', verbose_name='plasmid map (.gbk)'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='map_png',
            field=models.ImageField(blank=True, default='', upload_to='collection_management/huplasmid/png/', verbose_name='plasmid image'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='note',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='old_parent_vector',
            field=models.CharField(blank=True, default='', help_text='Use only when strictly necessary', max_length=255, verbose_name='orig. parent vector field'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='other_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='other name'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='received_from',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='selection',
            field=models.CharField(default='', max_length=50, verbose_name='selection'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='us_e',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='use'),
        ),
    ]
