# Generated by Django 2.1.8 on 2019-05-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0134_auto_20190522_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='a_pplication',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='application'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='catalogue_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='catalogue number'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='clone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='clone'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='description_comment',
            field=models.TextField(blank=True, default='', verbose_name='description/comments'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='l_ocation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='received_from',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='receieved from'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='species_isotype',
            field=models.CharField(default='', max_length=255, verbose_name='species/isotype'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='a_pplication',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='application'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='catalogue_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='catalogue number'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='clone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='clone'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='description_comment',
            field=models.TextField(blank=True, default='', verbose_name='description/comments'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='l_ocation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='received_from',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='receieved from'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='species_isotype',
            field=models.CharField(default='', max_length=255, verbose_name='species/isotype'),
        ),
    ]
