# Generated by Django 2.1.8 on 2019-06-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0010_auto_20190524_1723'),
        ('collection_management', '0136_auto_20190522_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsacerevisiaestrain',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], null=True, verbose_name='Risk group'),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='formz_projects',
            field=models.ManyToManyField(blank=True, related_name='cerevisiae_strain_projects', to='formz.FormZProject'),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], null=True, verbose_name='Risk group'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='created_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Destroyed'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='created_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Destroyed'),
        ),
    ]
