# Generated by Django 2.1.8 on 2019-06-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0137_auto_20190619_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsacerevisiaestrain',
            name='destroyed_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Destroyed'),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='destroyed_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Destroyed'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='created_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
    ]
