# Generated by Django 2.1.8 on 2019-06-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0139_auto_20190619_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsacerevisiaestrain',
            name='destroyed_date_time',
        ),
        migrations.RemoveField(
            model_name='sacerevisiaestrain',
            name='destroyed_date_time',
        ),
        migrations.AddField(
            model_name='historicalsacerevisiaestrain',
            name='destroyed_date',
            field=models.DateField(blank=True, null=True, verbose_name='destroyed'),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='destroyed_date',
            field=models.DateField(blank=True, null=True, verbose_name='destroyed'),
        ),
    ]
