# Generated by Django 2.1.8 on 2019-06-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0141_auto_20190619_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='formz_projects',
            field=models.ManyToManyField(blank=True, related_name='cerevisiae_strain_projects', to='formz.FormZProject', verbose_name='formZ projects'),
        ),
    ]
