# Generated by Django 2.1.8 on 2019-07-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0143_auto_20190705_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsacerevisiaestrain',
            name='history_all_plasmids_in_stocked_strain',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='history_all_plasmids_in_stocked_strain',
            field=models.TextField(blank=True),
        ),
    ]
