# Generated by Django 2.1.8 on 2019-07-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0144_auto_20190712_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsacerevisiaestrain',
            name='history_formz_projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='history_formz_projects',
            field=models.TextField(blank=True),
        ),
    ]
