# Generated by Django 2.1.8 on 2019-07-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0145_auto_20190712_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacerevisiaestrainepisomalplasmid',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='created'),
        ),
    ]
