# Generated by Django 2.1.8 on 2019-07-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0147_auto_20190715_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sacerevisiaestrainepisomalplasmid',
            old_name='created_date_time',
            new_name='created_date',
        ),
    ]
