# Generated by Django 2.1.8 on 2019-07-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0148_auto_20190715_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacerevisiaestrainepisomalplasmid',
            name='created_date',
            field=models.DateField(blank=True, null=True, verbose_name='created'),
        ),
    ]
