# Generated by Django 2.1.8 on 2019-07-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0013_remove_formzbaseelement_nuc_acid_type'),
        ('collection_management', '0149_auto_20190715_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhuplasmid',
            name='destroyed_date',
            field=models.DateField(blank=True, null=True, verbose_name='destroyed'),
        ),
        migrations.AddField(
            model_name='historicalhuplasmid',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
        migrations.AddField(
            model_name='historicalhuplasmid',
            name='history_formz_elements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalhuplasmid',
            name='history_formz_projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='huplasmid',
            name='destroyed_date',
            field=models.DateField(blank=True, null=True, verbose_name='destroyed'),
        ),
        migrations.AddField(
            model_name='huplasmid',
            name='formz_projects',
            field=models.ManyToManyField(blank=True, related_name='plasmid_formz_projects', to='formz.FormZProject', verbose_name='formZ projects'),
        ),
        migrations.AddField(
            model_name='huplasmid',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
        migrations.AddField(
            model_name='huplasmid',
            name='history_formz_elements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='huplasmid',
            name='history_formz_projects',
            field=models.TextField(blank=True),
        ),
    ]
