# Generated by Django 2.1.8 on 2019-07-19 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0016_zkbscellline_zkbsoncogene'),
        ('collection_management', '0151_auto_20190718_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmammalianline',
            name='destroyed_date',
            field=models.DateField(blank=True, null=True, verbose_name='destroyed'),
        ),
        migrations.AddField(
            model_name='historicalmammalianline',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
        migrations.AddField(
            model_name='historicalmammalianline',
            name='zkbs_cell_line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formz.ZkbsCellLine', verbose_name='ZKBS database cell line'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='destroyed_date',
            field=models.DateField(blank=True, null=True, verbose_name='destroyed'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='formz_projects',
            field=models.ManyToManyField(blank=True, related_name='mammalian_zprojects', to='formz.FormZProject', verbose_name='formZ projects'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='zkbs_cell_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formz.ZkbsCellLine', verbose_name='ZKBS database cell line'),
        ),
    ]
