# Generated by Django 2.1.8 on 2019-07-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0153_auto_20190719_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='history_all_plasmids_in_stocked_strain',
            field=models.TextField(blank=True, verbose_name='all plasmids in stocked strain'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='history_all_plasmids_in_stocked_strain',
            field=models.TextField(blank=True, verbose_name='all plasmids in stocked strain'),
        ),
    ]
