# Generated by Django 2.1.8 on 2019-07-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0154_auto_20190719_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacerevisiaestrainepisomalplasmid',
            name='destroyed_date',
            field=models.DateField(blank=True, null=True, verbose_name='created'),
        ),
    ]
