# Generated by Django 2.1.8 on 2019-07-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0017_formzbaseelement_zkbs_oncogene'),
        ('collection_management', '0156_auto_20190719_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='formz_gentech_methods',
            field=models.ManyToManyField(blank=True, related_name='cerevisiae_gentech_method', to='formz.GenTechMethod', verbose_name='genTech methods'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='formz_projects',
            field=models.ManyToManyField(blank=True, related_name='cerevisiae_formz_project', to='formz.FormZProject', verbose_name='formZ projects'),
        ),
    ]
