# Generated by Django 2.1.8 on 2019-07-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0160_auto_20190719_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='info_sheet',
            field=models.FileField(blank=True, help_text='max. 2 MB', null=True, upload_to='collection_management/antibody/', verbose_name='info sheet'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='info_sheet',
            field=models.TextField(blank=True, help_text='max. 2 MB', max_length=100, null=True, verbose_name='info sheet'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='map',
            field=models.TextField(blank=True, help_text='max. 2 MB', max_length=100, verbose_name='plasmid map'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='map',
            field=models.FileField(blank=True, help_text='max. 2 MB', upload_to='collection_management/huplasmid/dna/', verbose_name='plasmid map'),
        ),
        migrations.AlterField(
            model_name='mammalianlinedoc',
            name='name',
            field=models.FileField(help_text='max. 2 MB', null=True, upload_to='temp/', verbose_name='file name'),
        ),
    ]
