# Generated by Django 2.1.8 on 2019-07-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0028_auto_20190722_1116'),
        ('collection_management', '0163_auto_20190722_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='mammalianline',
            name='formz_elements',
            field=models.ManyToManyField(blank=True, help_text='Use only when an element is not present in one of the above-chosen plasmid(s), if any', related_name='mammalian_formz_element', to='formz.FormZBaseElement', verbose_name='elements'),
        ),
    ]
