# Generated by Django 2.1.8 on 2019-07-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0164_mammalianline_formz_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmammalianline',
            name='history_formz_elements',
            field=models.TextField(blank=True, verbose_name='formz elements'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='history_formz_elements',
            field=models.TextField(blank=True, verbose_name='formz elements'),
        ),
    ]
