# Generated by Django 2.1.8 on 2019-07-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0166_auto_20190722_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huplasmid',
            name='formz_elements',
            field=models.ManyToManyField(blank=True, help_text='<a href="/formz/formzbaseelement/" target="_blank">View/Change elements</a>', to='formz.FormZBaseElement', verbose_name='elements'),
        ),
    ]
