# Generated by Django 2.1.8 on 2019-07-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0171_auto_20190723_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmammalianline',
            name='s2_work',
            field=models.BooleanField(default=False, verbose_name='Used for S2 work?'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='s2_work',
            field=models.BooleanField(default=False, verbose_name='Used for S2 work?'),
        ),
    ]
