# Generated by Django 2.1.8 on 2019-07-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0174_auto_20190726_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mammalianlineepisomalplasmid',
            name='s2_work',
        ),
        migrations.AddField(
            model_name='mammalianlineepisomalplasmid',
            name='s2_work_episomal_plasmid',
            field=models.BooleanField(default=False, help_text='Check, for example, for lentiviral packaging plasmids', verbose_name='Used for S2 work?'),
        ),
    ]
