# Generated by Django 2.1.8 on 2019-07-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0175_auto_20190731_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacerevisiaestrainepisomalplasmid',
            name='present_in_stocked_strain',
            field=models.BooleanField(default=False, help_text="Choose 'Yes' if the culture you stocked for the -80° C collection contains an episomal plasmid. Choose 'No' if you just want to record that you have transiently transformed this strain with an episomal plasmid", null=True, verbose_name='present in -80° C stock?'),
        ),
    ]
