# Generated by Django 2.1.8 on 2019-08-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0180_auto_20190801_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huplasmid',
            name='formz_projects',
            field=models.ManyToManyField(blank=True, related_name='plasmid_formz_projects', to='formz.FormZProject', verbose_name='projects'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='formz_projects',
            field=models.ManyToManyField(blank=True, related_name='mammalian_zprojects', to='formz.FormZProject', verbose_name='projects'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='formz_projects',
            field=models.ManyToManyField(blank=True, related_name='cerevisiae_formz_project', to='formz.FormZProject', verbose_name='projects'),
        ),
    ]
