# Generated by Django 2.1.8 on 2019-09-06 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0186_auto_20190829_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='vector_zkbs',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The backbone of the plasmid, from the ZKBS database. If not applicable, choose none. <a href="/formz/zkbsplasmid/" target="_blank">View all</a>', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formz.ZkbsPlasmid', verbose_name='ZKBS database vector'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='zkbs_cell_line',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If not applicable, choose none. <a href="/formz/zkbscellline/" target="_blank">View all</a>', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formz.ZkbsCellLine', verbose_name='ZKBS database cell line'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='formz_ecoli_strains',
            field=models.ManyToManyField(default=14, related_name='plasmid_ecoli_strains', to='collection_management.EColiStrain', verbose_name='e. coli strains'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='formz_gentech_methods',
            field=models.ManyToManyField(blank=True, help_text='The methods used to create the plasmid', related_name='plasmid_gentech_method', to='formz.GenTechMethod', verbose_name='genTech methods'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='formz_projects',
            field=models.ManyToManyField(related_name='plasmid_formz_projects', to='formz.FormZProject', verbose_name='projects'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='vector_zkbs',
            field=models.ForeignKey(help_text='The backbone of the plasmid, from the ZKBS database. If not applicable, choose none. <a href="/formz/zkbsplasmid/" target="_blank">View all</a>', null=True, on_delete=django.db.models.deletion.PROTECT, to='formz.ZkbsPlasmid', verbose_name='ZKBS database vector'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='formz_gentech_methods',
            field=models.ManyToManyField(blank=True, help_text='The methods used to create the cell line', related_name='mammalian_gentech_method', to='formz.GenTechMethod', verbose_name='genTech methods'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='formz_projects',
            field=models.ManyToManyField(related_name='mammalian_zprojects', to='formz.FormZProject', verbose_name='projects'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='zkbs_cell_line',
            field=models.ForeignKey(help_text='If not applicable, choose none. <a href="/formz/zkbscellline/" target="_blank">View all</a>', null=True, on_delete=django.db.models.deletion.PROTECT, to='formz.ZkbsCellLine', verbose_name='ZKBS database cell line'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='formz_gentech_methods',
            field=models.ManyToManyField(blank=True, help_text='The methods used to create the strain', related_name='cerevisiae_gentech_method', to='formz.GenTechMethod', verbose_name='genTech methods'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='formz_projects',
            field=models.ManyToManyField(related_name='cerevisiae_formz_project', to='formz.FormZProject', verbose_name='projects'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='formz_gentech_methods',
            field=models.ManyToManyField(blank=True, help_text='The methods used to create the strain', related_name='pombe_gentech_method', to='formz.GenTechMethod', verbose_name='genTech methods'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='formz_projects',
            field=models.ManyToManyField(related_name='pombe_formz_project', to='formz.FormZProject', verbose_name='formZ projects'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
    ]
