# Generated by Django 2.1.8 on 2019-09-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0188_auto_20190906_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmammalianline',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical mammalian cell line'},
        ),
        migrations.AlterModelOptions(
            name='mammalianline',
            options={'verbose_name': 'mammalian cell line', 'verbose_name_plural': 'mammalian cell lines'},
        ),
    ]
