# Generated by Django 2.1.8 on 2019-10-03 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0194_auto_20191003_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='organism',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formz.Species', verbose_name='organism'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='organism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formz.Species', verbose_name='organism'),
        ),
    ]
