# Generated by Django 2.1.13 on 2019-10-31 09:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formz', '0073_auto_20191004_1937'),
        ('collection_management', '0195_auto_20191003_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalHuPlasmid',
            new_name='HistoricalPlasmid',
        ),
        migrations.RenameModel(
            old_name='HuPlasmid',
            new_name='Plasmid',
        ),
    ]
