# Generated by Django 2.1.13 on 2019-10-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0196_auto_20191031_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mammalianlineepisomalplasmid',
            old_name='huplasmid',
            new_name='plasmid',
        ),
        migrations.RenameField(
            model_name='sacerevisiaestrainepisomalplasmid',
            old_name='huplasmid',
            new_name='plasmid',
        ),
        migrations.RenameField(
            model_name='scpombestrainepisomalplasmid',
            old_name='huplasmid',
            new_name='plasmid',
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='map',
            field=models.FileField(blank=True, help_text='only .dna files, max. 2 MB', upload_to='collection_management/plasmid/dna/', verbose_name='plasmid map'),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='map_gbk',
            field=models.FileField(blank=True, upload_to='collection_management/plasmid/gb/', verbose_name='plasmid map (.gbk)'),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='map_png',
            field=models.ImageField(blank=True, upload_to='collection_management/plasmid/png/', verbose_name='plasmid image'),
        ),
    ]
