# Generated by Django 2.1.13 on 2019-11-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0204_auto_20191122_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasmid',
            name='formz_ecoli_strains',
            field=models.ManyToManyField(related_name='plasmid_ecoli_strains', to='collection_management.EColiStrain', verbose_name='e. coli strains'),
        ),
    ]
