# Generated by Django 2.2.7 on 2019-12-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0206_auto_20191217_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplasmid',
            name='map_gbk',
            field=models.TextField(blank=True, help_text='only .gbk files, max. 2 MB', max_length=100, verbose_name='plasmid map (.gbk)'),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='map_gbk',
            field=models.FileField(blank=True, help_text='only .gbk files, max. 2 MB', upload_to='collection_management/plasmid/gbk/', verbose_name='plasmid map (.gbk)'),
        ),
    ]
