# Generated by Django 3.1.6 on 2021-03-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0212_auto_20201020_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellline',
            name='last_changed_approval_by_pi',
            field=models.BooleanField(default=None, null=True, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='last_changed_approval_by_pi',
            field=models.BooleanField(default=None, null=True, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='historicalcellline',
            name='last_changed_approval_by_pi',
            field=models.BooleanField(default=None, null=True, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='last_changed_approval_by_pi',
            field=models.BooleanField(default=None, null=True, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='last_changed_approval_by_pi',
            field=models.BooleanField(default=None, null=True, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='historicalplasmid',
            name='last_changed_approval_by_pi',
            field=models.BooleanField(default=None, null=True, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='last_changed_approval_by_pi',
            field=models.BooleanField(default=None, null=True, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='last_changed_approval_by_pi',
            field=models.BooleanField(default=None, null=True, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='last_changed_approval_by_pi',
            field=models.BooleanField(default=None, null=True, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='last_changed_approval_by_pi',
            field=models.BooleanField(default=None, null=True, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='last_changed_approval_by_pi',
            field=models.BooleanField(default=None, null=True, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='last_changed_approval_by_pi',
            field=models.BooleanField(default=None, null=True, verbose_name='record change approval'),
        ),
    ]
