# Generated by Django 3.2.14 on 2022-07-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_labuser_is_principal_investigator'),
    ]

    operations = [
        migrations.AddField(
            model_name='labuser',
            name='identifier',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
