# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-04 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'cost unit',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255, verbose_name='Supplier')),
                ('supplier_part_no', models.CharField(max_length=255, verbose_name='Supplier Part-No')),
                ('part_description', models.CharField(max_length=255, verbose_name='Part Description')),
                ('quantity', models.CharField(max_length=255, verbose_name='Quantity')),
                ('price', models.CharField(blank=True, max_length=255, verbose_name='Price')),
                ('urgent', models.BooleanField(verbose_name='Is this an urgent order?')),
                ('delivery_alert', models.BooleanField(verbose_name='Would you like to receive a delivery alert for this order?')),
                ('comment', models.TextField(blank=True, verbose_name='Comments')),
                ('url', models.URLField(blank=True, max_length=400, verbose_name='URL')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('cost_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.CostUnit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.Location')),
            ],
        ),
    ]
