# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0007_auto_20181123_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='created_date_time',
            field=models.DateTimeField(verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date_time',
            field=models.DateTimeField(verbose_name='Created'),
        ),
    ]
