# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0009_auto_20181123_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='internal_order_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='Internal order number'),
        ),
        migrations.AddField(
            model_name='order',
            name='internal_order_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='Internal order number'),
        ),
    ]
