# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0015_auto_20181125_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalorder',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical order'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order'},
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='delivered_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Delivered'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='delivery_alert',
            field=models.BooleanField(default=False, verbose_name='Delivery notification?'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='urgent',
            field=models.BooleanField(default=False, verbose_name='Is this an urgent order?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Delivered'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_alert',
            field=models.BooleanField(default=False, verbose_name='Delivery notification?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='urgent',
            field=models.BooleanField(default=False, verbose_name='Is this an urgent order?'),
        ),
    ]
