# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0019_auto_20181126_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'submitted'), ('open', 'open'), ('arranged', 'arranged'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('used up', 'used up')], default='submitted', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'submitted'), ('open', 'open'), ('arranged', 'arranged'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('used up', 'used up')], default='submitted', max_length=255, verbose_name='Status'),
        ),
    ]
