# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0025_orderextradoc_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderextradoc',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
    ]
