# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0027_auto_20181213_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costunit',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
