# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-14 07:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0034_auto_20190113_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ordering.CostUnit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ordering.Location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='msds_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ordering.MsdsForm'),
        ),
        migrations.AlterField(
            model_name='orderextradoc',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordering.Order'),
        ),
    ]
