# Generated by Django 2.1.8 on 2019-08-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0042_auto_20190722_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costunit',
            name='status',
            field=models.BooleanField(default=False, help_text="Check it, if you want to HIDE this cost unit from the 'Add new order' form ", null=True, verbose_name='deactivate?'),
        ),
    ]
