# Generated by Django 2.1.8 on 2019-08-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0044_auto_20190826_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costunit',
            name='status',
            field=models.BooleanField(default=False, help_text="Check it, if you want to HIDE this cost unit from the 'Add new order' form", verbose_name='deactivate?'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='delivery_alert',
            field=models.BooleanField(default=False, verbose_name='delivery notification?'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='urgent',
            field=models.BooleanField(default=False, verbose_name='is this an urgent order?'),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.BooleanField(default=False, help_text="Check it, if you want to HIDE this location from the 'Add new order' form ", verbose_name='deactivate?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_alert',
            field=models.BooleanField(default=False, verbose_name='delivery notification?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='urgent',
            field=models.BooleanField(default=False, verbose_name='is this an urgent order?'),
        ),
    ]
