# Generated by Django 2.1.13 on 2019-11-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0045_auto_20190826_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='hazard_level_pregnancy',
            field=models.CharField(choices=[('none', 'none'), ('orange', 'orange'), ('red', 'red')], default='none', max_length=255, verbose_name='Hazard level for pregnancy'),
        ),
        migrations.AddField(
            model_name='order',
            name='hazard_level_pregnancy',
            field=models.CharField(choices=[('none', 'none'), ('orange', 'orange'), ('red', 'red')], default='none', max_length=255, verbose_name='Hazard level for pregnancy'),
        ),
    ]
