# Generated by Django 3.1.6 on 2021-05-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0051_auto_20210511_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalword',
            old_name='signal_words',
            new_name='signal_word',
        ),
    ]
