# Generated by Django 3.2.17 on 2023-08-01 07:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0055_auto_20221219_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('is_cmr', models.BooleanField(default=False, verbose_name='is CMR?')),
            ],
            options={
                'verbose_name': 'hazard statement',
            },
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='history_hazard_statements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='hazard statements'),
        ),
        migrations.AddField(
            model_name='order',
            name='history_hazard_statements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='hazard statements'),
        ),
        migrations.AddField(
            model_name='order',
            name='hazard_statements',
            field=models.ManyToManyField(blank=True, related_name='order_hazard_statement', to='ordering.HazardStatement', verbose_name='hazard statements'),
        ),
    ]
