# Generated by Django 4.2.4 on 2023-10-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0056_auto_20230801_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalorder',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical order', 'verbose_name_plural': 'historical orders'},
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
