# Generated by Django 4.2.4 on 2024-03-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0057_alter_historicalorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderextradoc',
            name='description',
            field=models.CharField(max_length=50, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='orderextradoc',
            name='name',
            field=models.FileField(null=True, upload_to='temp/', verbose_name='file name'),
        ),
    ]
