# Generated by Django 4.2.4 on 2024-03-27 09:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0058_alter_orderextradoc_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='history_ghs_symbols',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, null=True, size=None, verbose_name='GHS symbols'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='history_hazard_statements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, null=True, size=None, verbose_name='hazard statements'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='history_signal_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, null=True, size=None, verbose_name='signal words'),
        ),
        migrations.AlterField(
            model_name='order',
            name='history_ghs_symbols',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, null=True, size=None, verbose_name='GHS symbols'),
        ),
        migrations.AlterField(
            model_name='order',
            name='history_hazard_statements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, null=True, size=None, verbose_name='hazard statements'),
        ),
        migrations.AlterField(
            model_name='order',
            name='history_signal_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, null=True, size=None, verbose_name='signal words'),
        ),
    ]
