# Generated by Django 4.2.4 on 2024-04-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0059_alter_historicalorder_history_ghs_symbols_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderextradoc',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
    ]
