# Generated by Django 4.2.17 on 2025-01-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordering", "0060_alter_orderextradoc_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderextradoc",
            name="name",
            field=models.FileField(
                max_length=150, null=True, upload_to="temp/", verbose_name="file name"
            ),
        ),
    ]
