# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-05 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalhuplasmid',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical plasmid'},
        ),
        migrations.AlterModelOptions(
            name='huplasmid',
            options={'verbose_name': 'plasmid', 'verbose_name_plural': 'plasmids'},
        ),
    ]
