# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-30 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20180305_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antibody',
            old_name='application',
            new_name='a_pplication',
        ),
        migrations.RenameField(
            model_name='antibody',
            old_name='location',
            new_name='l_ocation',
        ),
        migrations.RenameField(
            model_name='historicalantibody',
            old_name='application',
            new_name='a_pplication',
        ),
        migrations.RenameField(
            model_name='historicalantibody',
            old_name='location',
            new_name='l_ocation',
        ),
    ]
