# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20180705_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmammalianline',
            name='parental_line',
        ),
        migrations.RemoveField(
            model_name='mammalianline',
            name='parental_line',
        ),
    ]
