# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_delete_mammalianlinedoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='MammalianLineDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(blank=True, upload_to='temp/', verbose_name='Info Sheet (max. 2 MB)')),
            ],
            options={
                'verbose_name': 'mammalian cell line document',
            },
        ),
        migrations.AddField(
            model_name='historicalmammalianline',
            name='document',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collection.MammalianLineDoc'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collection.MammalianLineDoc'),
            preserve_default=False,
        ),
    ]
