# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0021_auto_20180705_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mammalianline',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.MammalianLineDoc', verbose_name='Document (max. 2 MB)'),
        ),
    ]
