# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0022_auto_20180705_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmammalianlinedoc',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalmammalianlinedoc',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='mammalianlinedoc',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalmammalianline',
            name='document',
        ),
        migrations.RemoveField(
            model_name='mammalianline',
            name='document',
        ),
        migrations.DeleteModel(
            name='HistoricalMammalianLineDoc',
        ),
        migrations.DeleteModel(
            name='MammalianLineDoc',
        ),
    ]
