# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0024_historicalmammalianlinedoc_mammalianlinedoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmammalianlinedoc',
            name='date_of_test',
            field=models.DateField(verbose_name='Date of test'),
        ),
        migrations.AlterField(
            model_name='mammalianlinedoc',
            name='date_of_test',
            field=models.DateField(verbose_name='Date of test'),
        ),
    ]
