# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-06 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0031_auto_20180706_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mammalianline',
            name='parental_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.MammalianLine'),
        ),
    ]
