# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-12 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0041_auto_20180805_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsacerevisiaestrain',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='Record Creation Approval'),
        ),
        migrations.AddField(
            model_name='historicalsacerevisiaestrain',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='Record Change Approval'),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='Record Creation Approval'),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='Record Change Approval'),
        ),
    ]
