# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-02 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0047_auto_20181201_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecolistrain',
            name='approval_by_pi_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalecolistrain',
            name='approval_by_pi_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalhuplasmid',
            name='approval_by_pi_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalmammalianline',
            name='approval_by_pi_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalnzplasmid',
            name='approval_by_pi_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicaloligo',
            name='approval_by_pi_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalsacerevisiaestrain',
            name='approval_by_pi_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='approval_by_pi_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='huplasmid',
            name='approval_by_pi_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='approval_by_pi_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='nzplasmid',
            name='approval_by_pi_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='oligo',
            name='approval_by_pi_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='approval_by_pi_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='approval_by_pi_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
