# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0048_auto_20181202_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nzplasmid',
            name='plasmid_map',
            field=models.FileField(blank=True, upload_to='collection/nzplasmid/', verbose_name='Plasmid Map (max. 2 MB)'),
        ),
    ]
