# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0049_auto_20181208_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmammalianlinedoc',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmammalianlinedoc',
            name='mammalian_line',
        ),
        migrations.AlterField(
            model_name='antibody',
            name='info_sheet',
            field=models.FileField(blank=True, upload_to='collection/antibody/', verbose_name='Info sheet (max. 2 MB)'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='plasmid_map',
            field=models.FileField(blank=True, upload_to='collection/huplasmid/', verbose_name='Plasmid Map (max. 2 MB)'),
        ),
        migrations.DeleteModel(
            name='HistoricalMammalianLineDoc',
        ),
    ]
