# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0057_auto_20190412_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmammalianline',
            name='parental_line_new',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collection.MammalianLine'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='parental_line_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.MammalianLine'),
        ),
    ]
