# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0058_auto_20190412_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmammalianline',
            old_name='parental_line',
            new_name='parental_line_old',
        ),
        migrations.RenameField(
            model_name='mammalianline',
            old_name='parental_line',
            new_name='parental_line_old',
        ),
    ]
