# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0060_auto_20190412_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mammalianline',
            name='parental_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.MammalianLine', verbose_name='parental line'),
        ),
    ]
