# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0061_auto_20190412_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='a_pplication',
            field=models.CharField(blank=True, max_length=255, verbose_name='application'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='catalogue_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='catalogue number'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='clone',
            field=models.CharField(blank=True, max_length=255, verbose_name='clone'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='description_comment',
            field=models.TextField(blank=True, max_length=300, verbose_name='description/comments'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='info_sheet',
            field=models.FileField(blank=True, upload_to='collection/antibody/', verbose_name='info sheet (max. 2 MB)'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='l_ocation',
            field=models.CharField(blank=True, max_length=255, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='last_changed_date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='receieved from'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='species_isotype',
            field=models.CharField(max_length=255, verbose_name='species/isotype'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='record creation approval'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='genotype',
            field=models.TextField(blank=True, verbose_name='genotype'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='last_changed_date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='purpose',
            field=models.TextField(blank=True, verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='resistance',
            field=models.CharField(blank=True, max_length=255, verbose_name='resistance'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='us_e',
            field=models.CharField(choices=[('Cloning', 'Cloning'), ('Expression', 'Expression'), ('Other', 'Other')], max_length=255, verbose_name='use'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='a_pplication',
            field=models.CharField(blank=True, max_length=255, verbose_name='application'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='catalogue_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='catalogue number'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='clone',
            field=models.CharField(blank=True, max_length=255, verbose_name='clone'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='created_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='description_comment',
            field=models.TextField(blank=True, max_length=300, verbose_name='description/comments'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='info_sheet',
            field=models.TextField(blank=True, max_length=100, verbose_name='info sheet (max. 2 MB)'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='l_ocation',
            field=models.CharField(blank=True, max_length=255, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='last_changed_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='receieved from'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='species_isotype',
            field=models.CharField(max_length=255, verbose_name='species/isotype'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='record creation approval'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='created_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='genotype',
            field=models.TextField(blank=True, verbose_name='genotype'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='last_changed_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='purpose',
            field=models.TextField(blank=True, verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='resistance',
            field=models.CharField(blank=True, max_length=255, verbose_name='resistance'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='us_e',
            field=models.CharField(choices=[('Cloning', 'Cloning'), ('Expression', 'Expression'), ('Other', 'Other')], max_length=255, verbose_name='use'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='construction_feature',
            field=models.TextField(blank=True, verbose_name='construction/features'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='record creation approval'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='created_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='last_changed_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='note',
            field=models.CharField(blank=True, max_length=300, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='other_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='other name'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='parent_vector',
            field=models.CharField(blank=True, max_length=255, verbose_name='parent vector'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='plasmid_map',
            field=models.TextField(blank=True, max_length=100, verbose_name='plasmid map (max. 2 MB)'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='plasmid_map_gbk',
            field=models.TextField(blank=True, max_length=100, verbose_name='plasmid map (.gbk)'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='plasmid_map_png',
            field=models.TextField(blank=True, max_length=100, verbose_name='plasmid image'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='selection',
            field=models.CharField(max_length=50, verbose_name='selection'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='us_e',
            field=models.CharField(blank=True, max_length=255, verbose_name='use'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='alternative name'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='box_name',
            field=models.CharField(max_length=255, verbose_name='box'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='cell_type_tissue',
            field=models.CharField(blank=True, max_length=255, verbose_name='cell type/tissue'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='record creation approval'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='created_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='culture_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='culture type'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='description_comment',
            field=models.TextField(blank=True, max_length=300, verbose_name='description/comments'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='freezing_medium',
            field=models.CharField(blank=True, max_length=255, verbose_name='freezing medium'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='growth_condition',
            field=models.CharField(blank=True, max_length=255, verbose_name='growth conditions'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='last_changed_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='organism',
            field=models.CharField(blank=True, max_length=20, verbose_name='organism'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='parental_line_old',
            field=models.CharField(max_length=255, verbose_name='parental cell line'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='historicalnzplasmid',
            name='construction_feature',
            field=models.TextField(blank=True, verbose_name='construction/Features'),
        ),
        migrations.AlterField(
            model_name='historicalnzplasmid',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='record creation approval'),
        ),
        migrations.AlterField(
            model_name='historicalnzplasmid',
            name='created_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='historicalnzplasmid',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='historicalnzplasmid',
            name='last_changed_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='historicalnzplasmid',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalnzplasmid',
            name='other_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='other name'),
        ),
        migrations.AlterField(
            model_name='historicalnzplasmid',
            name='parent_vector',
            field=models.CharField(blank=True, max_length=255, verbose_name='parent vector'),
        ),
        migrations.AlterField(
            model_name='historicalnzplasmid',
            name='plasmid_map',
            field=models.TextField(blank=True, max_length=100, verbose_name='plasmid map (max. 2 MB)'),
        ),
        migrations.AlterField(
            model_name='historicalnzplasmid',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='historicalnzplasmid',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='historicalnzplasmid',
            name='selection',
            field=models.CharField(max_length=50, verbose_name='selection'),
        ),
        migrations.AlterField(
            model_name='historicalnzplasmid',
            name='us_e',
            field=models.CharField(blank=True, max_length=255, verbose_name='use'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='record creation approval'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='created_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='gene',
            field=models.CharField(blank=True, max_length=255, verbose_name='gene'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='last_changed_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='length',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='restriction_site',
            field=models.CharField(blank=True, max_length=255, verbose_name='restriction sites'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='sequence',
            field=models.CharField(db_index=True, max_length=255, verbose_name='sequence'),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='us_e',
            field=models.CharField(blank=True, max_length=255, verbose_name='use'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='background',
            field=models.CharField(blank=True, max_length=255, verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='chromosomal_genotype',
            field=models.TextField(blank=True, verbose_name='chromosomal genotype'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='construction',
            field=models.TextField(blank=True, verbose_name='construction'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='record creation approval'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='created_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='last_changed_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='mating_type',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('alpha', 'alpha'), ('unknown', 'unknown'), ('a/a', 'a/a'), ('alpha/alpha', 'alpha/alpha'), ('a/alpha', 'a/alpha')], max_length=20, verbose_name='mating type'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='modification',
            field=models.CharField(blank=True, max_length=255, verbose_name='modification'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='parental_strain',
            field=models.CharField(blank=True, max_length=255, verbose_name='parental strain'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='phenotype',
            field=models.CharField(blank=True, max_length=255, verbose_name='phenotype'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='plasmids',
            field=models.CharField(blank=True, max_length=255, verbose_name='plasmids'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='relevant_genotype',
            field=models.CharField(max_length=255, verbose_name='relevant genotype'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='selection',
            field=models.CharField(blank=True, max_length=255, verbose_name='selection'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='us_e',
            field=models.CharField(blank=True, max_length=255, verbose_name='use'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='auxotrophic_marker',
            field=models.CharField(blank=True, max_length=255, verbose_name='auxotrophic markers'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='box_number',
            field=models.SmallIntegerField(verbose_name='box number'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='record creation approval'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='created_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='last_changed_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='mating_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='mating type'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='name',
            field=models.TextField(verbose_name='genotype'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='parental_strain',
            field=models.CharField(blank=True, max_length=255, verbose_name='parental strains'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='phenotype',
            field=models.CharField(blank=True, max_length=255, verbose_name='phenotype'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='construction_feature',
            field=models.TextField(blank=True, verbose_name='construction/features'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='record creation approval'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='last_changed_date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='note',
            field=models.CharField(blank=True, max_length=300, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='other_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='other name'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='parent_vector',
            field=models.CharField(blank=True, max_length=255, verbose_name='parent vector'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='plasmid_map',
            field=models.FileField(blank=True, upload_to='collection/huplasmid/dna/', verbose_name='plasmid map (max. 2 MB)'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='plasmid_map_gbk',
            field=models.FileField(blank=True, upload_to='collection/huplasmid/gb/', verbose_name='plasmid map (.gbk)'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='plasmid_map_png',
            field=models.ImageField(blank=True, upload_to='collection/huplasmid/png/', verbose_name='plasmid image'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='selection',
            field=models.CharField(max_length=50, verbose_name='selection'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='us_e',
            field=models.CharField(blank=True, max_length=255, verbose_name='use'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='alternative name'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='box_name',
            field=models.CharField(max_length=255, verbose_name='box'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='cell_type_tissue',
            field=models.CharField(blank=True, max_length=255, verbose_name='cell type/tissue'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='record creation approval'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='culture_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='culture type'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='description_comment',
            field=models.TextField(blank=True, max_length=300, verbose_name='description/comments'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='freezing_medium',
            field=models.CharField(blank=True, max_length=255, verbose_name='freezing medium'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='growth_condition',
            field=models.CharField(blank=True, max_length=255, verbose_name='growth conditions'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='last_changed_date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='organism',
            field=models.CharField(blank=True, max_length=20, verbose_name='organism'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='parental_line_old',
            field=models.CharField(max_length=255, verbose_name='parental cell line'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='mammalianlinedoc',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='mammalianlinedoc',
            name='date_of_test',
            field=models.DateField(verbose_name='date of test'),
        ),
        migrations.AlterField(
            model_name='mammalianlinedoc',
            name='last_changed_date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last Changed'),
        ),
        migrations.AlterField(
            model_name='mammalianlinedoc',
            name='name',
            field=models.FileField(upload_to='temp/', verbose_name='file name'),
        ),
        migrations.AlterField(
            model_name='mammalianlinedoc',
            name='typ_e',
            field=models.CharField(choices=[['virus', 'Virus test'], ['mycoplasma', 'Mycoplasma test'], ['fingerprint', 'Fingerprinting'], ['other', 'Other']], max_length=255, verbose_name='doc type'),
        ),
        migrations.AlterField(
            model_name='nzplasmid',
            name='construction_feature',
            field=models.TextField(blank=True, verbose_name='construction/Features'),
        ),
        migrations.AlterField(
            model_name='nzplasmid',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='record creation approval'),
        ),
        migrations.AlterField(
            model_name='nzplasmid',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='nzplasmid',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='nzplasmid',
            name='last_changed_date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='nzplasmid',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='nzplasmid',
            name='other_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='other name'),
        ),
        migrations.AlterField(
            model_name='nzplasmid',
            name='parent_vector',
            field=models.CharField(blank=True, max_length=255, verbose_name='parent vector'),
        ),
        migrations.AlterField(
            model_name='nzplasmid',
            name='plasmid_map',
            field=models.FileField(blank=True, upload_to='collection/nzplasmid/', verbose_name='plasmid map (max. 2 MB)'),
        ),
        migrations.AlterField(
            model_name='nzplasmid',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='nzplasmid',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='nzplasmid',
            name='selection',
            field=models.CharField(max_length=50, verbose_name='selection'),
        ),
        migrations.AlterField(
            model_name='nzplasmid',
            name='us_e',
            field=models.CharField(blank=True, max_length=255, verbose_name='use'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='record creation approval'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='gene',
            field=models.CharField(blank=True, max_length=255, verbose_name='gene'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='last_changed_date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='length',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='restriction_site',
            field=models.CharField(blank=True, max_length=255, verbose_name='restriction sites'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='sequence',
            field=models.CharField(max_length=255, unique=True, verbose_name='sequence'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='us_e',
            field=models.CharField(blank=True, max_length=255, verbose_name='use'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='background',
            field=models.CharField(blank=True, max_length=255, verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='chromosomal_genotype',
            field=models.TextField(blank=True, verbose_name='chromosomal genotype'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='construction',
            field=models.TextField(blank=True, verbose_name='construction'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='record creation approval'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='last_changed_date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='mating_type',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('alpha', 'alpha'), ('unknown', 'unknown'), ('a/a', 'a/a'), ('alpha/alpha', 'alpha/alpha'), ('a/alpha', 'a/alpha')], max_length=20, verbose_name='mating type'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='modification',
            field=models.CharField(blank=True, max_length=255, verbose_name='modification'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='parental_strain',
            field=models.CharField(blank=True, max_length=255, verbose_name='parental strain'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='phenotype',
            field=models.CharField(blank=True, max_length=255, verbose_name='phenotype'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='plasmids',
            field=models.CharField(blank=True, max_length=255, verbose_name='plasmids'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='relevant_genotype',
            field=models.CharField(max_length=255, verbose_name='relevant genotype'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='selection',
            field=models.CharField(blank=True, max_length=255, verbose_name='selection'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='us_e',
            field=models.CharField(blank=True, max_length=255, verbose_name='use'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='auxotrophic_marker',
            field=models.CharField(blank=True, max_length=255, verbose_name='auxotrophic markers'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='box_number',
            field=models.SmallIntegerField(verbose_name='box number'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='created_approval_by_pi',
            field=models.BooleanField(default=False, verbose_name='record creation approval'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='last_changed_approval_by_pi',
            field=models.NullBooleanField(default=None, verbose_name='record change approval'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='last_changed_date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='mating_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='mating type'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='name',
            field=models.TextField(verbose_name='genotype'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='parental_strain',
            field=models.CharField(blank=True, max_length=255, verbose_name='parental strains'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='phenotype',
            field=models.CharField(blank=True, max_length=255, verbose_name='phenotype'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='received from'),
        ),
    ]
