# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0069_auto_20190416_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huplasmid',
            name='formz_elements',
            field=models.ManyToManyField(to='formz.FormZBaseElement', verbose_name='Elements'),
        ),
    ]
