# Generated by Django 2.1.8 on 2019-04-21 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0072_auto_20190416_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsacerevisiaestrain',
            name='parent_1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collection.SaCerevisiaeStrain'),
        ),
        migrations.AddField(
            model_name='historicalsacerevisiaestrain',
            name='parent_2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collection.SaCerevisiaeStrain'),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='cassette_plasmids',
            field=models.ManyToManyField(blank=True, help_text='Tagging and knock out plasmids', to='collection.HuPlasmid'),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='integrated_plasmids',
            field=models.ManyToManyField(blank=True, related_name='sa_cerevisiae_strain', to='collection.HuPlasmid'),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='parent_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sa_cerevisiae_strain', to='collection.SaCerevisiaeStrain', verbose_name='Parent 1'),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='parent_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collection.SaCerevisiaeStrain', verbose_name='Parent 2'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='plasmids',
            field=models.CharField(blank=True, help_text='Use only when the other plasmid fields do not apply', max_length=255, verbose_name='plasmids'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='plasmids',
            field=models.CharField(blank=True, help_text='Use only when the other plasmid fields do not apply', max_length=255, verbose_name='plasmids'),
        ),
    ]
