# Generated by Django 2.1.8 on 2019-04-21 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0073_auto_20190421_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='integrated_plasmids',
            field=models.ManyToManyField(blank=True, related_name='integrated_pl', to='collection.HuPlasmid'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='parent_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_strain_1', to='collection.SaCerevisiaeStrain', verbose_name='Parent 1'),
        ),
    ]
