# Generated by Django 2.1.8 on 2019-04-24 17:03

from django.db import migrations, models, connection
import django.db.models.deletion

def alter_table(apps, schema_editor):
    query ="ALTER TABLE collection_mammalianline ADD UNIQUE (name);"
    cursor = connection.cursor()
    cursor.execute(query)
    cursor.close()

class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0079_auto_20190424_1701'),
    ]

    operations = [migrations.RunPython(alter_table),]