# Generated by Django 2.1.8 on 2019-04-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0080_auto_20190424_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='mammalianline',
            name='integrated_plasmids',
            field=models.ManyToManyField(blank=True, related_name='int_pl', to='collection.HuPlasmid'),
        ),
    ]
