# Generated by Django 2.1.8 on 2019-04-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0082_auto_20190424_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='parent_vector',
            field=models.CharField(blank=True, max_length=255, verbose_name='old parent vector'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='parent_vector',
            field=models.CharField(blank=True, max_length=255, verbose_name='old parent vector'),
        ),
    ]
