# Generated by Django 2.1.8 on 2019-05-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0088_auto_20190426_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
