# Generated by Django 2.1.8 on 2019-05-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0089_auto_20190517_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
