# Generated by Django 2.1.8 on 2019-05-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0090_auto_20190517_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaCerevisiaeStrainEpisomalPlasmid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('huplasmid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.HuPlasmid')),
                ('sacerevisiae_strain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.SaCerevisiaeStrain')),
            ],
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='episomal_plasmids',
            field=models.ManyToManyField(blank=True, related_name='episomal_pl', through='collection.SaCerevisiaeStrainEpisomalPlasmid', to='collection.HuPlasmid'),
        ),
    ]
