# Generated by Django 2.1.8 on 2019-05-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0096_auto_20190519_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacerevisiaestrainepisomalplasmid',
            name='formz_project',
            field=models.ManyToManyField(blank=True, null=True, related_name='sc_epi_plasmid', to='formz.FormZProject'),
        ),
    ]
