# Generated by Django 2.1.8 on 2019-05-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0102_auto_20190520_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mammalianline',
            name='integrated_plasmids',
            field=models.ManyToManyField(blank=True, related_name='mammalian_integrated_plasmids', to='collection.HuPlasmid'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='cassette_plasmids',
            field=models.ManyToManyField(blank=True, help_text='Tagging and knock out plasmids', related_name='cerevisiae_cassette_plasmids', to='collection.HuPlasmid'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='episomal_plasmids',
            field=models.ManyToManyField(blank=True, related_name='cerevisiae_episomal_plasmids', through='collection.SaCerevisiaeStrainEpisomalPlasmid', to='collection.HuPlasmid'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='integrated_plasmids',
            field=models.ManyToManyField(blank=True, related_name='cerevisiae_integrated_plasmids', to='collection.HuPlasmid'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='cassette_plasmids',
            field=models.ManyToManyField(blank=True, help_text='Tagging and knock out plasmids', related_name='pombe_cassette_plasmids', to='collection.HuPlasmid'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='integrated_plasmids',
            field=models.ManyToManyField(blank=True, related_name='pombe_integrated_plasmids', to='collection.HuPlasmid'),
        ),
    ]
