# Generated by Django 2.1.8 on 2019-05-21 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0104_auto_20190521_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='parent_1',
            field=models.ForeignKey(blank=True, help_text='Main parental strain', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cerevisiae_parent_1', to='collection.SaCerevisiaeStrain', verbose_name='Parent 1'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='parent_2',
            field=models.ForeignKey(blank=True, help_text='Only for crosses', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cerevisiae_parent_2', to='collection.SaCerevisiaeStrain', verbose_name='Parent 2'),
        ),
    ]
