# Generated by Django 2.1.8 on 2019-05-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0106_auto_20190521_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sacerevisiaestrainepisomalplasmid',
            old_name='formz_project',
            new_name='formz_projects',
        ),
    ]
