# Generated by Django 2.1.8 on 2019-05-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0110_auto_20190521_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scpombestrain',
            name='cassette_plasmids',
            field=models.ManyToManyField(blank=True, help_text='Tagging and knock out plasmids', related_name='pombe_cassette_plasmids', to='collection.HuPlasmid'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='integrated_plasmids',
            field=models.ManyToManyField(blank=True, related_name='pombe_integrated_plasmids', to='collection.HuPlasmid'),
        ),
    ]
