# Generated by Django 2.1.8 on 2019-05-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0113_auto_20190521_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalhuplasmid',
            old_name='plasmid_map',
            new_name='map',
        ),
        migrations.RenameField(
            model_name='historicalhuplasmid',
            old_name='plasmid_map_gbk',
            new_name='map_gbk',
        ),
        migrations.RenameField(
            model_name='historicalhuplasmid',
            old_name='plasmid_map_png',
            new_name='map_png',
        ),
        migrations.RenameField(
            model_name='huplasmid',
            old_name='plasmid_map',
            new_name='map',
        ),
        migrations.RenameField(
            model_name='huplasmid',
            old_name='plasmid_map_gbk',
            new_name='map_gbk',
        ),
        migrations.RenameField(
            model_name='huplasmid',
            old_name='plasmid_map_png',
            new_name='map_png',
        ),
    ]
