# Generated by Django 2.1.8 on 2019-05-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0117_auto_20190522_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='chromosomal_genotype',
            field=models.TextField(blank=True, default='', verbose_name='chromosomal genotype'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='construction',
            field=models.TextField(blank=True, default='', verbose_name='construction'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='mating_type',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('alpha', 'alpha'), ('unknown', 'unknown'), ('a/a', 'a/a'), ('alpha/alpha', 'alpha/alpha'), ('a/alpha', 'a/alpha')], default='', max_length=20, verbose_name='mating type'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='modification',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='modification'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='parental_strain',
            field=models.CharField(blank=True, default='', help_text="Use only when 'Parent 1' does not apply", max_length=255, verbose_name='parental strain'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='phenotype',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='phenotype'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='plasmids',
            field=models.CharField(blank=True, default='', help_text='Use only when the other plasmid fields do not apply', max_length=255, verbose_name='plasmids'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='received_from',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='relevant_genotype',
            field=models.CharField(default='', max_length=255, verbose_name='relevant genotype'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='selection',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='selection'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='us_e',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='use'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='chromosomal_genotype',
            field=models.TextField(blank=True, default='', verbose_name='chromosomal genotype'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='construction',
            field=models.TextField(blank=True, default='', verbose_name='construction'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='mating_type',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('alpha', 'alpha'), ('unknown', 'unknown'), ('a/a', 'a/a'), ('alpha/alpha', 'alpha/alpha'), ('a/alpha', 'a/alpha')], default='', max_length=20, verbose_name='mating type'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='modification',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='modification'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='parental_strain',
            field=models.CharField(blank=True, default='', help_text="Use only when 'Parent 1' does not apply", max_length=255, verbose_name='parental strain'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='phenotype',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='phenotype'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='plasmids',
            field=models.CharField(blank=True, default='', help_text='Use only when the other plasmid fields do not apply', max_length=255, verbose_name='plasmids'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='received_from',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='relevant_genotype',
            field=models.CharField(default='', max_length=255, verbose_name='relevant genotype'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='selection',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='selection'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='us_e',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='use'),
        ),
    ]
