# Generated by Django 2.1.8 on 2019-05-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0129_auto_20190522_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecolistrain',
            name='genotype',
            field=models.TextField(blank=True, verbose_name='genotype'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='purpose',
            field=models.TextField(blank=True, verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='resistance',
            field=models.CharField(blank=True, max_length=255, verbose_name='resistance'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='supplier',
            field=models.CharField(max_length=255, verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='us_e',
            field=models.CharField(choices=[('Cloning', 'Cloning'), ('Expression', 'Expression'), ('Other', 'Other')], max_length=255, verbose_name='use'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='genotype',
            field=models.TextField(blank=True, verbose_name='genotype'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='purpose',
            field=models.TextField(blank=True, verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='resistance',
            field=models.CharField(blank=True, max_length=255, verbose_name='resistance'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='supplier',
            field=models.CharField(max_length=255, verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='us_e',
            field=models.CharField(choices=[('Cloning', 'Cloning'), ('Expression', 'Expression'), ('Other', 'Other')], max_length=255, verbose_name='use'),
        ),
    ]
