# Generated by Django 2.1.8 on 2019-05-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0130_auto_20190522_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='alternative_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='alternative name'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='box_name',
            field=models.CharField(default='', max_length=255, verbose_name='box'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='cell_type_tissue',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='cell type/tissue'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='culture_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='culture type'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='description_comment',
            field=models.TextField(blank=True, default='', verbose_name='description/comments'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='freezing_medium',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='freezing medium'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='growth_condition',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='growth conditions'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='organism',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='organism'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='parental_line_old',
            field=models.CharField(default='', max_length=255, verbose_name='parental cell line'),
        ),
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='received_from',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='alternative_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='alternative name'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='box_name',
            field=models.CharField(default='', max_length=255, verbose_name='box'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='cell_type_tissue',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='cell type/tissue'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='culture_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='culture type'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='description_comment',
            field=models.TextField(blank=True, default='', verbose_name='description/comments'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='freezing_medium',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='freezing medium'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='growth_condition',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='growth conditions'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='organism',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='organism'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='parental_line_old',
            field=models.CharField(default='', max_length=255, verbose_name='parental cell line'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='received_from',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='received from'),
        ),
    ]
