# Generated by Django 2.1.8 on 2019-05-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0132_auto_20190522_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mammalianlinedoc',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='mammalianlinedoc',
            name='typ_e',
            field=models.CharField(choices=[['virus', 'Virus test'], ['mycoplasma', 'Mycoplasma test'], ['fingerprint', 'Fingerprinting'], ['other', 'Other']], default='', max_length=255, verbose_name='doc type'),
        ),
    ]
