# Generated by Django 2.1.8 on 2019-06-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0140_auto_20190619_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
    ]
