# Generated by Django 2.1.8 on 2019-07-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0142_auto_20190619_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsacerevisiaestrain',
            name='history_cassette_plasmids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalsacerevisiaestrain',
            name='history_episomal_plasmids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalsacerevisiaestrain',
            name='history_integrated_plasmids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='history_cassette_plasmids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='history_episomal_plasmids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='history_integrated_plasmids',
            field=models.TextField(blank=True),
        ),
    ]
