# Generated by Django 2.1.8 on 2019-07-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0158_auto_20190719_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsacerevisiaestrain',
            old_name='history_gentech_methods',
            new_name='history_formz_gentech_methods',
        ),
        migrations.RenameField(
            model_name='sacerevisiaestrain',
            old_name='history_gentech_methods',
            new_name='history_formz_gentech_methods',
        ),
    ]
