# Generated by Django 2.1.8 on 2019-07-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0017_formzbaseelement_zkbs_oncogene'),
        ('collection', '0159_auto_20190719_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsacerevisiaestrain',
            name='history_formz_elements',
            field=models.TextField(blank=True, verbose_name='formz elements'),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='formz_elements',
            field=models.ManyToManyField(blank=True, help_text='Use only when an element is not present in one of the above-chosen plasmid(s), if any', related_name='cerevisiae_formz_element', to='formz.FormZBaseElement', verbose_name='elements'),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='history_formz_elements',
            field=models.TextField(blank=True, verbose_name='formz elements'),
        ),
    ]
