# Generated by Django 2.1.8 on 2019-07-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0161_auto_20190722_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='info_sheet',
            field=models.FileField(blank=True, help_text='only .pdf files, max. 2 MB', null=True, upload_to='collection/antibody/', verbose_name='info sheet'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='info_sheet',
            field=models.TextField(blank=True, help_text='only .pdf files, max. 2 MB', max_length=100, null=True, verbose_name='info sheet'),
        ),
        migrations.AlterField(
            model_name='historicalhuplasmid',
            name='map',
            field=models.TextField(blank=True, help_text='only .dna files, max. 2 MB', max_length=100, verbose_name='plasmid map'),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='map',
            field=models.FileField(blank=True, help_text='only .dna files, max. 2 MB', upload_to='collection/huplasmid/dna/', verbose_name='plasmid map'),
        ),
    ]
