# Generated by Django 2.1.8 on 2019-07-22 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0028_auto_20190722_1116'),
        ('collection', '0162_auto_20190722_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='MammalianLineEpisomalPlasmid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(null=True, verbose_name='created')),
                ('destroyed_date', models.DateField(blank=True, null=True, verbose_name='destroyed')),
                ('formz_projects', models.ManyToManyField(blank=True, related_name='mammalian_episomal_plasmid_projects', to='formz.FormZProject')),
            ],
        ),
        migrations.CreateModel(
            name='ScPombeStrainEpisomalPlasmid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_in_stocked_strain', models.BooleanField(default=False, null=True, verbose_name='present in -80° C stock?')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='created')),
                ('destroyed_date', models.DateField(blank=True, null=True, verbose_name='destroyed')),
                ('formz_projects', models.ManyToManyField(blank=True, related_name='pombe_episomal_plasmid_projects', to='formz.FormZProject')),
            ],
        ),
        migrations.AddField(
            model_name='historicalhuplasmid',
            name='history_formz_gentech_methods',
            field=models.TextField(blank=True, verbose_name='genTech methods'),
        ),
        migrations.AddField(
            model_name='historicalmammalianline',
            name='history_documents',
            field=models.TextField(blank=True, verbose_name='document'),
        ),
        migrations.AddField(
            model_name='historicalmammalianline',
            name='history_episomal_plasmids',
            field=models.TextField(blank=True, verbose_name='episomal plasmids'),
        ),
        migrations.AddField(
            model_name='historicalmammalianline',
            name='history_formz_gentech_methods',
            field=models.TextField(blank=True, verbose_name='genTech methods'),
        ),
        migrations.AddField(
            model_name='historicalmammalianline',
            name='history_formz_projects',
            field=models.TextField(blank=True, verbose_name='formZ projects'),
        ),
        migrations.AddField(
            model_name='historicalmammalianline',
            name='history_integrated_plasmids',
            field=models.TextField(blank=True, verbose_name='integrated plasmid'),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='destroyed_date',
            field=models.DateField(blank=True, null=True, verbose_name='destroyed'),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='history_all_plasmids_in_stocked_strain',
            field=models.TextField(blank=True, verbose_name='all plasmids in stocked strain'),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='history_cassette_plasmids',
            field=models.TextField(blank=True, verbose_name='cassette plasmids'),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='history_episomal_plasmids',
            field=models.TextField(blank=True, verbose_name='episomal plasmids'),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='history_formz_elements',
            field=models.TextField(blank=True, verbose_name='formz elements'),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='history_formz_gentech_methods',
            field=models.TextField(blank=True, verbose_name='genTech methods'),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='history_formz_projects',
            field=models.TextField(blank=True, verbose_name='formZ projects'),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='history_integrated_plasmids',
            field=models.TextField(blank=True, verbose_name='integrated plasmid'),
        ),
        migrations.AddField(
            model_name='huplasmid',
            name='formz_gentech_methods',
            field=models.ManyToManyField(blank=True, related_name='plasmid_gentech_method', to='formz.GenTechMethod', verbose_name='genTech methods'),
        ),
        migrations.AddField(
            model_name='huplasmid',
            name='history_formz_gentech_methods',
            field=models.TextField(blank=True, verbose_name='genTech methods'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='formz_gentech_methods',
            field=models.ManyToManyField(blank=True, related_name='mammalian_gentech_method', to='formz.GenTechMethod', verbose_name='genTech methods'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='history_documents',
            field=models.TextField(blank=True, verbose_name='document'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='history_episomal_plasmids',
            field=models.TextField(blank=True, verbose_name='episomal plasmids'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='history_formz_gentech_methods',
            field=models.TextField(blank=True, verbose_name='genTech methods'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='history_formz_projects',
            field=models.TextField(blank=True, verbose_name='formZ projects'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='history_integrated_plasmids',
            field=models.TextField(blank=True, verbose_name='integrated plasmid'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='destroyed_date',
            field=models.DateField(blank=True, null=True, verbose_name='destroyed'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='formz_elements',
            field=models.ManyToManyField(blank=True, help_text='Use only when an element is not present in one of the above-chosen plasmid(s), if any', related_name='pombe_formz_element', to='formz.FormZBaseElement', verbose_name='elements'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='formz_gentech_methods',
            field=models.ManyToManyField(blank=True, related_name='pombe_gentech_method', to='formz.GenTechMethod', verbose_name='genTech methods'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='formz_projects',
            field=models.ManyToManyField(blank=True, related_name='pombe_formz_project', to='formz.FormZProject', verbose_name='formZ projects'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='formz_risk_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='history_all_plasmids_in_stocked_strain',
            field=models.TextField(blank=True, verbose_name='all plasmids in stocked strain'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='history_cassette_plasmids',
            field=models.TextField(blank=True, verbose_name='cassette plasmids'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='history_episomal_plasmids',
            field=models.TextField(blank=True, verbose_name='episomal plasmids'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='history_formz_elements',
            field=models.TextField(blank=True, verbose_name='formz elements'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='history_formz_gentech_methods',
            field=models.TextField(blank=True, verbose_name='genTech methods'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='history_formz_projects',
            field=models.TextField(blank=True, verbose_name='formZ projects'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='history_integrated_plasmids',
            field=models.TextField(blank=True, verbose_name='integrated plasmid'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrainepisomalplasmid',
            name='formz_projects',
            field=models.ManyToManyField(blank=True, related_name='cerevisiae_episomal_plasmid_projects', to='formz.FormZProject'),
        ),
        migrations.AddField(
            model_name='scpombestrainepisomalplasmid',
            name='huplasmid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.HuPlasmid', verbose_name='Plasmid'),
        ),
        migrations.AddField(
            model_name='scpombestrainepisomalplasmid',
            name='scpombe_strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.ScPombeStrain'),
        ),
        migrations.AddField(
            model_name='mammalianlineepisomalplasmid',
            name='huplasmid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.HuPlasmid', verbose_name='Plasmid'),
        ),
        migrations.AddField(
            model_name='mammalianlineepisomalplasmid',
            name='mammalian_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.MammalianLine'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='episomal_plasmids',
            field=models.ManyToManyField(blank=True, related_name='mammalian_episomal_plasmids', through='collection.MammalianLineEpisomalPlasmid', to='collection.HuPlasmid'),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='episomal_plasmids',
            field=models.ManyToManyField(blank=True, related_name='pombe_episomal_plasmids', through='collection.ScPombeStrainEpisomalPlasmid', to='collection.HuPlasmid'),
        ),
    ]
