# Generated by Django 2.1.8 on 2019-07-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0173_auto_20190726_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhuplasmid',
            name='vector_known_zkbs',
        ),
        migrations.RemoveField(
            model_name='huplasmid',
            name='vector_known_zkbs',
        ),
    ]
