# Generated by Django 2.1.8 on 2019-08-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0178_auto_20190801_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacerevisiaestrainepisomalplasmid',
            name='present_in_stocked_strain',
            field=models.BooleanField(default=False, help_text="Choose 'Yes', if the culture you stocked for the -80° C collection contains an episomal plasmid. Choose 'No', if you simply want to record that you have transiently transformed this strain with an episomal plasmid", verbose_name='present in -80° C stock?'),
        ),
        migrations.AlterField(
            model_name='scpombestrainepisomalplasmid',
            name='present_in_stocked_strain',
            field=models.BooleanField(default=False, verbose_name='present in -80° C stock?'),
        ),
    ]
