# Generated by Django 2.1.8 on 2019-08-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0181_auto_20190801_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='organism',
            field=models.CharField(blank=True, help_text='Use full species name, e.g. Homo sapiens', max_length=20, verbose_name='organism'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='organism',
            field=models.CharField(blank=True, help_text='Use full species name, e.g. Homo sapiens', max_length=20, verbose_name='organism'),
        ),
    ]
