# Generated by Django 2.1.8 on 2019-08-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0184_auto_20190807_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecolistrain',
            name='risk_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
        migrations.AddField(
            model_name='historicalecolistrain',
            name='risk_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True, verbose_name='risk group'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='background',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('K12', 'K12'), ('W', 'W')], max_length=255, verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='note',
            field=models.TextField(blank=True, max_length=255, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='background',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('K12', 'K12'), ('W', 'W')], max_length=255, verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='note',
            field=models.TextField(blank=True, max_length=255, verbose_name='note'),
        ),
    ]
