# Generated by Django 2.1.8 on 2019-09-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0187_auto_20190906_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmammalianline',
            name='s2_work',
            field=models.BooleanField(default=False, help_text='Check, for example, for a cell line created by lentiviral trunsdunction', verbose_name='Used for S2 work?'),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='s2_work',
            field=models.BooleanField(default=False, help_text='Check, for example, for a cell line created by lentiviral trunsdunction', verbose_name='Used for S2 work?'),
        ),
    ]
