# Generated by Django 2.1.8 on 2019-09-14 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0057_auto_20190914_1705'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0189_auto_20190911_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecolistrain',
            name='approval_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coli_approval_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ecolistrain',
            name='formz_projects',
            field=models.ManyToManyField(default=1, related_name='coli_formz_project', to='formz.FormZProject', verbose_name='formZ projects'),
        ),
        migrations.AddField(
            model_name='historicalecolistrain',
            name='approval_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhuplasmid',
            name='approval_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmammalianline',
            name='approval_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaloligo',
            name='approval_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsacerevisiaestrain',
            name='approval_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscpombestrain',
            name='approval_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='huplasmid',
            name='approval_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plasmid_approval_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='approval_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mammalian_approval_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oligo',
            name='approval_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oligo_approval_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sacerevisiaestrain',
            name='approval_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cerevisiae_approval_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scpombestrain',
            name='approval_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pombe_approval_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coli_createdby_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='huplasmid',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plasmid_createdby_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mammalianline',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mammalian_createdby_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oligo_createdby_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cerevisiae_createdby_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pombe_createdby_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
