# Generated by Django 2.1.8 on 2019-09-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0190_auto_20190914_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloligo',
            name='approval_user',
        ),
        migrations.RemoveField(
            model_name='oligo',
            name='approval_user',
        ),
    ]
