# Generated by Django 2.1.8 on 2019-10-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0067_formzstoragelocation_species_name'),
        ('collection', '0191_auto_20190916_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmammalianline',
            name='organism_species',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formz.Species', verbose_name='species name'),
        ),
        migrations.AddField(
            model_name='mammalianline',
            name='organism_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formz.Species', verbose_name='species name'),
        ),
    ]
