# Generated by Django 2.1.8 on 2019-10-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0193_auto_20191003_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmammalianline',
            old_name='organism_species',
            new_name='organism',
        ),
        migrations.RenameField(
            model_name='mammalianline',
            old_name='organism_species',
            new_name='organism',
        ),
    ]
