# Generated by Django 2.1.13 on 2019-11-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0198_auto_20191117_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecolistrain',
            old_name='risk_group',
            new_name='formz_risk_group',
        ),
        migrations.RenameField(
            model_name='historicalecolistrain',
            old_name='risk_group',
            new_name='formz_risk_group',
        ),
    ]
