# Generated by Django 2.1.13 on 2019-11-22 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formz', '0078_auto_20191117_1549'),
        ('collection', '0199_auto_20191117_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MammalianLine',
            new_name='CellLine',
        ),
        migrations.RenameModel(
            old_name='HistoricalMammalianLine',
            new_name='HistoricalCellLine',
        ),
    ]
