# Generated by Django 2.1.13 on 2019-11-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0201_auto_20191122_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MammalianLineDoc',
            new_name='CellLineDoc',
        ),
    ]
