# Generated by Django 2.1.13 on 2019-11-22 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0202_auto_20191122_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cellline',
            options={'verbose_name': 'cell line', 'verbose_name_plural': 'cell lines'},
        ),
        migrations.AlterModelOptions(
            name='celllinedoc',
            options={'verbose_name': 'cell line document'},
        ),
        migrations.AlterModelOptions(
            name='historicalcellline',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical cell line'},
        ),
        migrations.AlterField(
            model_name='cellline',
            name='approval_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cellline_approval_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cellline',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cellline_createdby_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cellline',
            name='episomal_plasmids',
            field=models.ManyToManyField(blank=True, related_name='cellline_episomal_plasmids', through='collection.CellLineEpisomalPlasmid', to='collection.Plasmid'),
        ),
        migrations.AlterField(
            model_name='cellline',
            name='formz_elements',
            field=models.ManyToManyField(blank=True, help_text='Use only when an element is not present in the chosen plasmid(s), if any', related_name='cellline_formz_element', to='formz.FormZBaseElement', verbose_name='elements'),
        ),
        migrations.AlterField(
            model_name='cellline',
            name='formz_gentech_methods',
            field=models.ManyToManyField(blank=True, help_text='The methods used to create the cell line', related_name='cellline_gentech_method', to='formz.GenTechMethod', verbose_name='genTech methods'),
        ),
        migrations.AlterField(
            model_name='cellline',
            name='formz_projects',
            field=models.ManyToManyField(related_name='cellline_zprojects', to='formz.FormZProject', verbose_name='projects'),
        ),
        migrations.AlterField(
            model_name='cellline',
            name='integrated_plasmids',
            field=models.ManyToManyField(blank=True, related_name='cellline_integrated_plasmids', to='collection.Plasmid'),
        ),
        migrations.AlterField(
            model_name='celllineepisomalplasmid',
            name='formz_projects',
            field=models.ManyToManyField(blank=True, related_name='cellline_episomal_plasmid_projects', to='formz.FormZProject'),
        ),
    ]
