# Generated by Django 2.1.13 on 2019-11-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0203_auto_20191122_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celllinedoc',
            old_name='mammalian_line',
            new_name='cell_line',
        ),
        migrations.RenameField(
            model_name='celllineepisomalplasmid',
            old_name='mammalian_line',
            new_name='cell_line',
        ),
    ]
