# Generated by Django 2.2.7 on 2019-12-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0207_auto_20191218_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplasmid',
            name='map',
            field=models.TextField(blank=True, help_text='only SnapGene .dna files, max. 2 MB', max_length=100, verbose_name='plasmid map (.dna)'),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='map',
            field=models.FileField(blank=True, help_text='only SnapGene .dna files, max. 2 MB', upload_to='collection/plasmid/dna/', verbose_name='plasmid map (.dna)'),
        ),
    ]
