# Generated by Django 2.2.13 on 2020-06-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0210_auto_20200119_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='received from'),
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='received from'),
        ),
    ]
