# Generated by Django 2.2.13 on 2020-10-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0211_auto_20200623_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellline',
            name='formz_elements',
            field=models.ManyToManyField(blank=True, help_text='Use only when an element is not present in the chosen plasmid(s), if any. Searching against the aliases of an element is case-sensitive. <a href="/formz/formzbaseelement/" target="_blank">View all/Change</a>', related_name='cellline_formz_element', to='formz.FormZBaseElement', verbose_name='elements'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='formz_elements',
            field=models.ManyToManyField(blank=True, help_text='Searching against the aliases of an element is case-sensitive. <a href="/formz/formzbaseelement/" target="_blank">View all/Change</a>', related_name='coli_formz_element', to='formz.FormZBaseElement', verbose_name='elements'),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='formz_elements',
            field=models.ManyToManyField(blank=True, help_text='Searching against the aliases of an element is case-sensitive. <a href="/formz/formzbaseelement/" target="_blank">View all/Change</a>', to='formz.FormZBaseElement', verbose_name='elements'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='formz_elements',
            field=models.ManyToManyField(blank=True, help_text='Use only when an element is not present in the chosen plasmid(s), if any. Searching against the aliases of an element is case-sensitive. <a href="/formz/formzbaseelement/" target="_blank">View all/Change</a>', related_name='cerevisiae_formz_element', to='formz.FormZBaseElement', verbose_name='elements'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='formz_elements',
            field=models.ManyToManyField(blank=True, help_text='Use only when an element is not present in the chosen plasmid(s), if any. Searching against the aliases of an element is case-sensitive. <a href="/formz/formzbaseelement/" target="_blank">View all/Change</a>', related_name='pombe_formz_element', to='formz.FormZBaseElement', verbose_name='elements'),
        ),
    ]
