# Generated by Django 3.2.15 on 2022-12-19 12:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0215_auto_20221212_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellline',
            name='history_documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='documents'),
        ),
        migrations.AlterField(
            model_name='cellline',
            name='history_episomal_plasmids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='episomal plasmids'),
        ),
        migrations.AlterField(
            model_name='cellline',
            name='history_formz_elements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formz elements'),
        ),
        migrations.AlterField(
            model_name='cellline',
            name='history_formz_gentech_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='genTech methods'),
        ),
        migrations.AlterField(
            model_name='cellline',
            name='history_formz_projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formZ projects'),
        ),
        migrations.AlterField(
            model_name='cellline',
            name='history_integrated_plasmids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='integrated plasmid'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='history_formz_elements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formz elements'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='history_formz_gentech_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='genTech methods'),
        ),
        migrations.AlterField(
            model_name='ecolistrain',
            name='history_formz_projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formZ projects'),
        ),
        migrations.AlterField(
            model_name='historicalcellline',
            name='history_documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='documents'),
        ),
        migrations.AlterField(
            model_name='historicalcellline',
            name='history_episomal_plasmids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='episomal plasmids'),
        ),
        migrations.AlterField(
            model_name='historicalcellline',
            name='history_formz_elements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formz elements'),
        ),
        migrations.AlterField(
            model_name='historicalcellline',
            name='history_formz_gentech_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='genTech methods'),
        ),
        migrations.AlterField(
            model_name='historicalcellline',
            name='history_formz_projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formZ projects'),
        ),
        migrations.AlterField(
            model_name='historicalcellline',
            name='history_integrated_plasmids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='integrated plasmid'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='history_formz_elements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formz elements'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='history_formz_gentech_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='genTech methods'),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='history_formz_projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formZ projects'),
        ),
        migrations.AlterField(
            model_name='historicalplasmid',
            name='history_formz_ecoli_strains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='e. coli strains'),
        ),
        migrations.AlterField(
            model_name='historicalplasmid',
            name='history_formz_elements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formz elements'),
        ),
        migrations.AlterField(
            model_name='historicalplasmid',
            name='history_formz_gentech_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='genTech methods'),
        ),
        migrations.AlterField(
            model_name='historicalplasmid',
            name='history_formz_projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formZ projects'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='history_all_plasmids_in_stocked_strain',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='all plasmids in stocked strain'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='history_cassette_plasmids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='cassette plasmids'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='history_episomal_plasmids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='episomal plasmids'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='history_formz_elements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formz elements'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='history_formz_gentech_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='genTech methods'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='history_formz_projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formZ projects'),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='history_integrated_plasmids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='integrated plasmid'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='history_all_plasmids_in_stocked_strain',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='all plasmids in stocked strain'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='history_cassette_plasmids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='cassette plasmids'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='history_episomal_plasmids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='episomal plasmids'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='history_formz_elements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formz elements'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='history_formz_gentech_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='genTech methods'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='history_formz_projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formZ projects'),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='history_integrated_plasmids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='integrated plasmid'),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='history_formz_ecoli_strains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='e. coli strains'),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='history_formz_elements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formz elements'),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='history_formz_gentech_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='genTech methods'),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='history_formz_projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formZ projects'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='history_all_plasmids_in_stocked_strain',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='all plasmids in stocked strain'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='history_cassette_plasmids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='cassette plasmids'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='history_episomal_plasmids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='episomal plasmids'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='history_formz_elements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formz elements'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='history_formz_gentech_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='genTech methods'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='history_formz_projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formZ projects'),
        ),
        migrations.AlterField(
            model_name='sacerevisiaestrain',
            name='history_integrated_plasmids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='integrated plasmid'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='history_all_plasmids_in_stocked_strain',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='all plasmids in stocked strain'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='history_cassette_plasmids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='cassette plasmids'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='history_episomal_plasmids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='episomal plasmids'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='history_formz_elements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formz elements'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='history_formz_gentech_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='genTech methods'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='history_formz_projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formZ projects'),
        ),
        migrations.AlterField(
            model_name='scpombestrain',
            name='history_integrated_plasmids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='integrated plasmid'),
        ),
    ]
