# Generated by Django 4.2.4 on 2023-10-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0216_auto_20221219_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalantibody',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical antibody', 'verbose_name_plural': 'historical antibodies'},
        ),
        migrations.AlterModelOptions(
            name='historicalcellline',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical cell line', 'verbose_name_plural': 'historical cell lines'},
        ),
        migrations.AlterModelOptions(
            name='historicalecolistrain',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical strain - E. coli', 'verbose_name_plural': 'historical strains - E. coli'},
        ),
        migrations.AlterModelOptions(
            name='historicaloligo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical oligo', 'verbose_name_plural': 'historical oligos'},
        ),
        migrations.AlterModelOptions(
            name='historicalplasmid',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical plasmid', 'verbose_name_plural': 'historical plasmids'},
        ),
        migrations.AlterModelOptions(
            name='historicalsacerevisiaestrain',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical strain - Sa. cerevisiae', 'verbose_name_plural': 'historical strains - Sa. cerevisiae'},
        ),
        migrations.AlterModelOptions(
            name='historicalscpombestrain',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical strain - Sc. pombe', 'verbose_name_plural': 'historical strains - Sc. pombe'},
        ),
        migrations.AlterField(
            model_name='historicalantibody',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcellline',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalecolistrain',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaloligo',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalplasmid',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsacerevisiaestrain',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalscpombestrain',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
