# Generated by Django 4.2.4 on 2024-01-24 17:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formz', '0082_auto_20230104_1520'),
        ('collection', '0217_alter_historicalantibody_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloligo',
            name='history_formz_elements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formz elements'),
        ),
        migrations.AddField(
            model_name='oligo',
            name='formz_elements',
            field=models.ManyToManyField(blank=True, related_name='oligo_formz_element', to='formz.formzbaseelement', verbose_name='elements'),
        ),
        migrations.AddField(
            model_name='oligo',
            name='history_formz_elements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='formz elements'),
        ),
    ]
