# Generated by Django 4.2.4 on 2024-01-30 11:44

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0219_wormstrain_wormstraingenotypingassay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inhibitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('other_names', models.CharField(max_length=255, verbose_name='other names')),
                ('target', models.CharField(blank=True, max_length=255, verbose_name='target')),
                ('received_from', models.CharField(blank=True, max_length=255, verbose_name='received from')),
                ('catalogue_number', models.CharField(blank=True, max_length=255, verbose_name='catalogue number')),
                ('l_ocation', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('ic50', models.CharField(blank=True, max_length=255, verbose_name='IC50')),
                ('amount', models.CharField(blank=True, max_length=255, verbose_name='amount')),
                ('stock_solution', models.CharField(blank=True, max_length=255, verbose_name='stock solution')),
                ('description_comment', models.TextField(blank=True, verbose_name='description/comments')),
                ('info_sheet', models.FileField(blank=True, help_text='only .pdf files, max. 2 MB', null=True, upload_to='collection/inhibitor/', verbose_name='info sheet')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_changed_date_time', models.DateTimeField(auto_now=True, verbose_name='last changed')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inhibitor',
                'verbose_name_plural': 'inhibitors',
            },
            bases=(models.Model, common.models.SaveWithoutHistoricalRecord),
        ),
        migrations.CreateModel(
            name='HistoricalInhibitor',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('other_names', models.CharField(max_length=255, verbose_name='other names')),
                ('target', models.CharField(blank=True, max_length=255, verbose_name='target')),
                ('received_from', models.CharField(blank=True, max_length=255, verbose_name='received from')),
                ('catalogue_number', models.CharField(blank=True, max_length=255, verbose_name='catalogue number')),
                ('l_ocation', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('ic50', models.CharField(blank=True, max_length=255, verbose_name='IC50')),
                ('amount', models.CharField(blank=True, max_length=255, verbose_name='amount')),
                ('stock_solution', models.CharField(blank=True, max_length=255, verbose_name='stock solution')),
                ('description_comment', models.TextField(blank=True, verbose_name='description/comments')),
                ('info_sheet', models.TextField(blank=True, help_text='only .pdf files, max. 2 MB', max_length=100, null=True, verbose_name='info sheet')),
                ('created_date_time', models.DateTimeField(blank=True, editable=False, verbose_name='created')),
                ('last_changed_date_time', models.DateTimeField(blank=True, editable=False, verbose_name='last changed')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical inhibitor',
                'verbose_name_plural': 'historical inhibitors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
