# Generated by Django 4.2.4 on 2024-02-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0220_inhibitor_historicalinhibitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloligo',
            name='info_sheet',
            field=models.TextField(blank=True, help_text='only .pdf files, max. 2 MB', max_length=100, null=True, verbose_name='info sheet'),
        ),
        migrations.AddField(
            model_name='oligo',
            name='info_sheet',
            field=models.FileField(blank=True, help_text='only .pdf files, max. 2 MB', null=True, upload_to='collection/oligo/', verbose_name='info sheet'),
        ),
    ]
