# Generated by Django 4.2.4 on 2024-02-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0223_sirna_historicalsirna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsirna',
            name='sequence',
            field=models.CharField(help_text='Sense strand', max_length=50, verbose_name='sequence'),
        ),
        migrations.AlterField(
            model_name='sirna',
            name='sequence',
            field=models.CharField(help_text='Sense strand', max_length=50, verbose_name='sequence'),
        ),
    ]
