# Generated by Django 4.2.4 on 2024-02-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0224_alter_historicalsirna_sequence_alter_oligo_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oligo',
            name='sequence',
            field=models.CharField(db_collation='case_insensitive', max_length=255, unique=True, verbose_name='sequence'),
        ),
    ]
