# Generated by Django 4.2.4 on 2024-04-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0228_historicalsirna_sequence_antisense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsirna',
            name='sequence',
            field=models.CharField(max_length=50, verbose_name='sequence - Sense'),
        ),
        migrations.AlterField(
            model_name='historicalsirna',
            name='sequence_antisense',
            field=models.CharField(max_length=50, verbose_name='sequence - Antisense'),
        ),
        migrations.AlterField(
            model_name='sirna',
            name='sequence',
            field=models.CharField(max_length=50, verbose_name='sequence - Sense'),
        ),
        migrations.AlterField(
            model_name='sirna',
            name='sequence_antisense',
            field=models.CharField(max_length=50, verbose_name='sequence - Antisense'),
        ),
    ]
