# Generated by Django 4.2.4 on 2024-04-11 07:30

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0229_alter_historicalsirna_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsirna',
            name='locus_ids',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, null=True, size=None, verbose_name='locus IDs'),
        ),
        migrations.AlterField(
            model_name='sirna',
            name='locus_ids',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, null=True, size=None, verbose_name='locus IDs'),
        ),
    ]
