# Generated by Django 4.2.4 on 2024-08-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("formz", "0082_auto_20230104_1520"),
        (
            "collection",
            "0231_rename_history_integrated_oligos_historicalwormstrain_history_integrated_dna_oligos_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cellline",
            name="organism",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="formz.species",
                verbose_name="organism",
            ),
        ),
    ]
