# Generated by Django 4.2.4 on 2024-10-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0233_historicalwormstrainallele_history_documents_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ecolistrain",
            name="history_formz_gentech_methods",
        ),
        migrations.RemoveField(
            model_name="historicalecolistrain",
            name="history_formz_gentech_methods",
        ),
        migrations.AlterField(
            model_name="ecolistrain",
            name="formz_risk_group",
            field=models.PositiveSmallIntegerField(
                choices=[(1, 1), (2, 2)], null=True, verbose_name="risk group"
            ),
        ),
        migrations.AlterField(
            model_name="historicalecolistrain",
            name="formz_risk_group",
            field=models.PositiveSmallIntegerField(
                choices=[(1, 1), (2, 2)], null=True, verbose_name="risk group"
            ),
        ),
    ]
