# Generated by Django 4.2.4 on 2024-12-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0235_alter_oligo_options_alter_antibody_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalwormstrain",
            name="location_backup",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="location Backup"
            ),
        ),
        migrations.AlterField(
            model_name="historicalwormstrain",
            name="location_freezer1",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="location Freezer 1"
            ),
        ),
        migrations.AlterField(
            model_name="historicalwormstrain",
            name="location_freezer2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="location Freezer 2"
            ),
        ),
        migrations.AlterField(
            model_name="wormstrain",
            name="location_backup",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="location Backup"
            ),
        ),
        migrations.AlterField(
            model_name="wormstrain",
            name="location_freezer1",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="location Freezer 1"
            ),
        ),
        migrations.AlterField(
            model_name="wormstrain",
            name="location_freezer2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="location Freezer 2"
            ),
        ),
    ]
