# Generated by Django 4.2.17 on 2025-01-15 09:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("formz", "0082_auto_20230104_1520"),
        ("collection", "0237_alter_historicalwormstrainallele_lab_identifier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalwormstrainallele",
            name="note",
        ),
        migrations.RemoveField(
            model_name="historicalwormstrainallele",
            name="transgene_plasmids",
        ),
        migrations.RemoveField(
            model_name="wormstrainallele",
            name="note",
        ),
        migrations.AddField(
            model_name="historicalwormstrainallele",
            name="history_made_with_plasmids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="made with plasmids",
            ),
        ),
        migrations.AddField(
            model_name="historicalwormstrainallele",
            name="history_transgene_plasmids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="transgene plasmids",
            ),
        ),
        migrations.AddField(
            model_name="historicalwormstrainallele",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AddField(
            model_name="wormstrainallele",
            name="history_made_with_plasmids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="made with plasmids",
            ),
        ),
        migrations.AddField(
            model_name="wormstrainallele",
            name="history_transgene_plasmids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="transgene plasmids",
            ),
        ),
        migrations.AddField(
            model_name="wormstrainallele",
            name="made_with_plasmids",
            field=models.ManyToManyField(
                blank=True,
                help_text="The plasmid(s) used to create the transgene/mutation",
                to="collection.plasmid",
                verbose_name="made with plasmids",
            ),
        ),
        migrations.AddField(
            model_name="wormstrainallele",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="historicalwormstrainallele",
            name="made_by_method",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The method(s) used to create the allele",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="formz.gentechmethod",
                verbose_name="made by method",
            ),
        ),
        migrations.AlterField(
            model_name="wormstrainallele",
            name="made_by_method",
            field=models.ForeignKey(
                help_text="The method(s) used to create the allele",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_made_by_method",
                to="formz.gentechmethod",
                verbose_name="made by method",
            ),
        ),
        migrations.RemoveField(
            model_name="wormstrainallele",
            name="transgene_plasmids",
        ),
        migrations.AddField(
            model_name="wormstrainallele",
            name="transgene_plasmids",
            field=models.ManyToManyField(
                blank=True,
                help_text="The plasmid(s) in the transgene",
                related_name="%(class)s_transgene_plasmids",
                to="collection.plasmid",
                verbose_name="transgene plasmids",
            ),
        ),
    ]
