# Generated by Django 4.2.17 on 2025-01-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("formz", "0082_auto_20230104_1520"),
        ("collection", "0238_remove_historicalwormstrainallele_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalwormstrainallele",
            name="made_by_method",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The method used to create the allele",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="formz.gentechmethod",
                verbose_name="made by method",
            ),
        ),
        migrations.AlterField(
            model_name="wormstrainallele",
            name="made_by_method",
            field=models.ForeignKey(
                help_text="The method used to create the allele",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_made_by_method",
                to="formz.gentechmethod",
                verbose_name="made by method",
            ),
        ),
    ]
