# Generated by Django 4.2.17 on 2025-01-15 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0239_alter_historicalwormstrainallele_made_by_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wormstrainallele",
            name="reference_strain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_reference_strain",
                to="collection.wormstrain",
                verbose_name="reference strain",
            ),
        ),
    ]
