# Generated by Django 4.2.17 on 2025-01-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0240_alter_wormstrainallele_reference_strain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibodydoc",
            name="name",
            field=models.FileField(
                max_length=150, null=True, upload_to="temp/", verbose_name="file name"
            ),
        ),
        migrations.AlterField(
            model_name="celllinedoc",
            name="name",
            field=models.FileField(
                max_length=150, null=True, upload_to="temp/", verbose_name="file name"
            ),
        ),
        migrations.AlterField(
            model_name="ecolistraindoc",
            name="name",
            field=models.FileField(
                max_length=150, null=True, upload_to="temp/", verbose_name="file name"
            ),
        ),
        migrations.AlterField(
            model_name="inhibitordoc",
            name="name",
            field=models.FileField(
                max_length=150, null=True, upload_to="temp/", verbose_name="file name"
            ),
        ),
        migrations.AlterField(
            model_name="oligodoc",
            name="name",
            field=models.FileField(
                max_length=150, null=True, upload_to="temp/", verbose_name="file name"
            ),
        ),
        migrations.AlterField(
            model_name="plasmiddoc",
            name="name",
            field=models.FileField(
                max_length=150, null=True, upload_to="temp/", verbose_name="file name"
            ),
        ),
        migrations.AlterField(
            model_name="sacerevisiaestraindoc",
            name="name",
            field=models.FileField(
                max_length=150, null=True, upload_to="temp/", verbose_name="file name"
            ),
        ),
        migrations.AlterField(
            model_name="scpombestraindoc",
            name="name",
            field=models.FileField(
                max_length=150, null=True, upload_to="temp/", verbose_name="file name"
            ),
        ),
        migrations.AlterField(
            model_name="sirnadoc",
            name="name",
            field=models.FileField(
                max_length=150, null=True, upload_to="temp/", verbose_name="file name"
            ),
        ),
        migrations.AlterField(
            model_name="wormstrainalleledoc",
            name="name",
            field=models.FileField(
                max_length=150, null=True, upload_to="temp/", verbose_name="file name"
            ),
        ),
        migrations.AlterField(
            model_name="wormstraindoc",
            name="name",
            field=models.FileField(
                max_length=150, null=True, upload_to="temp/", verbose_name="file name"
            ),
        ),
    ]
