# Generated by Django 4.2.17 on 2025-01-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0241_alter_antibodydoc_name_alter_celllinedoc_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibodydoc",
            name="description",
            field=models.CharField(max_length=75, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="ecolistraindoc",
            name="description",
            field=models.CharField(max_length=75, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="inhibitordoc",
            name="description",
            field=models.CharField(max_length=75, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="oligodoc",
            name="description",
            field=models.CharField(max_length=75, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="plasmiddoc",
            name="description",
            field=models.CharField(max_length=75, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="sacerevisiaestraindoc",
            name="description",
            field=models.CharField(max_length=75, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="scpombestraindoc",
            name="description",
            field=models.CharField(max_length=75, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="sirnadoc",
            name="description",
            field=models.CharField(max_length=75, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="wormstrainalleledoc",
            name="description",
            field=models.CharField(max_length=75, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="wormstraindoc",
            name="description",
            field=models.CharField(max_length=75, verbose_name="description"),
        ),
    ]
