# Generated by Django 4.2.17 on 2025-01-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0242_alter_antibodydoc_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwormstrain",
            name="at_cgc",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="at CGC?"
            ),
        ),
        migrations.AddField(
            model_name="wormstrain",
            name="at_cgc",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="at CGC?"
            ),
        ),
    ]
