# Generated by Django 4.2.17 on 2025-01-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0243_historicalwormstrain_at_cgc_wormstrain_at_cgc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalwormstrain",
            name="phenotype",
            field=models.TextField(blank=True, verbose_name="phenotype"),
        ),
        migrations.AlterField(
            model_name="wormstrain",
            name="phenotype",
            field=models.TextField(blank=True, verbose_name="phenotype"),
        ),
    ]
