# Generated by Django 4.2.17 on 2025-03-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "formz",
            "0084_rename_formz_base_element_sequenceelementalias_sequence_element",
        ),
        (
            "collection",
            "0246_rename_history_formz_elements_cellline_history_sequence_elements_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cellline",
            name="sequence_elements",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when an element is not present in the chosen plasmid(s), if any. Searching against the aliases of an element is case-sensitive. <a href="/formz/formzbaseelement/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_elements",
                to="formz.sequenceelement",
                verbose_name="elements",
            ),
        ),
        migrations.AlterField(
            model_name="ecolistrain",
            name="sequence_elements",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when an element is not present in the chosen plasmid(s), if any. Searching against the aliases of an element is case-sensitive. <a href="/formz/formzbaseelement/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_elements",
                to="formz.sequenceelement",
                verbose_name="elements",
            ),
        ),
        migrations.AlterField(
            model_name="oligo",
            name="sequence_elements",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_sequence_elements",
                to="formz.sequenceelement",
                verbose_name="elements",
            ),
        ),
        migrations.AlterField(
            model_name="plasmid",
            name="sequence_elements",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when an element is not present in the chosen plasmid(s), if any. Searching against the aliases of an element is case-sensitive. <a href="/formz/formzbaseelement/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_elements",
                to="formz.sequenceelement",
                verbose_name="elements",
            ),
        ),
        migrations.AlterField(
            model_name="sacerevisiaestrain",
            name="sequence_elements",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when an element is not present in the chosen plasmid(s), if any. Searching against the aliases of an element is case-sensitive. <a href="/formz/formzbaseelement/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_elements",
                to="formz.sequenceelement",
                verbose_name="elements",
            ),
        ),
        migrations.AlterField(
            model_name="scpombestrain",
            name="sequence_elements",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when an element is not present in the chosen plasmid(s), if any. Searching against the aliases of an element is case-sensitive. <a href="/formz/formzbaseelement/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_elements",
                to="formz.sequenceelement",
                verbose_name="elements",
            ),
        ),
        migrations.AlterField(
            model_name="wormstrain",
            name="sequence_elements",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when an element is not present in the chosen plasmid(s), if any. Searching against the aliases of an element is case-sensitive. <a href="/formz/formzbaseelement/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_elements",
                to="formz.sequenceelement",
                verbose_name="elements",
            ),
        ),
    ]
