# Generated by Django 4.2.17 on 2025-03-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formz", "0086_rename_sequenceelement_sequencefeature_and_more"),
        ("collection", "0249_alter_cellline_sequence_elements_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cellline",
            name="sequence_features",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when an element is not present in the chosen plasmid(s), if any. Searching against the aliases of an element is case-sensitive. <a href="/formz/sequencefeature/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_features",
                to="formz.sequencefeature",
                verbose_name="sequence features",
            ),
        ),
        migrations.AlterField(
            model_name="ecolistrain",
            name="sequence_features",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when an element is not present in the chosen plasmid(s), if any. Searching against the aliases of an element is case-sensitive. <a href="/formz/sequencefeature/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_features",
                to="formz.sequencefeature",
                verbose_name="sequence features",
            ),
        ),
        migrations.AlterField(
            model_name="plasmid",
            name="sequence_features",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when an element is not present in the chosen plasmid(s), if any. Searching against the aliases of an element is case-sensitive. <a href="/formz/sequencefeature/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_features",
                to="formz.sequencefeature",
                verbose_name="sequence features",
            ),
        ),
        migrations.AlterField(
            model_name="sacerevisiaestrain",
            name="sequence_features",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when an element is not present in the chosen plasmid(s), if any. Searching against the aliases of an element is case-sensitive. <a href="/formz/sequencefeature/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_features",
                to="formz.sequencefeature",
                verbose_name="sequence features",
            ),
        ),
        migrations.AlterField(
            model_name="scpombestrain",
            name="sequence_features",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when an element is not present in the chosen plasmid(s), if any. Searching against the aliases of an element is case-sensitive. <a href="/formz/sequencefeature/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_features",
                to="formz.sequencefeature",
                verbose_name="sequence features",
            ),
        ),
        migrations.AlterField(
            model_name="wormstrain",
            name="sequence_features",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when an element is not present in the chosen plasmid(s), if any. Searching against the aliases of an element is case-sensitive. <a href="/formz/sequencefeature/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_features",
                to="formz.sequencefeature",
                verbose_name="sequence features",
            ),
        ),
    ]
