# Generated by Django 4.2.17 on 2025-03-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formz", "0087_alter_sequencefeaturealias_options"),
        ("collection", "0250_alter_cellline_sequence_features_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cellline",
            name="sequence_features",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when a feature is not present in the chosen plasmid(s), if any. Searching against the aliases of a feature is case-sensitive. <a href="/formz/sequencefeature/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_features",
                to="formz.sequencefeature",
                verbose_name="sequence features",
            ),
        ),
        migrations.AlterField(
            model_name="ecolistrain",
            name="sequence_features",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when a feature is not present in the chosen plasmid(s), if any. Searching against the aliases of a feature is case-sensitive. <a href="/formz/sequencefeature/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_features",
                to="formz.sequencefeature",
                verbose_name="sequence features",
            ),
        ),
        migrations.AlterField(
            model_name="plasmid",
            name="sequence_features",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when a feature is not present in the chosen plasmid(s), if any. Searching against the aliases of a feature is case-sensitive. <a href="/formz/sequencefeature/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_features",
                to="formz.sequencefeature",
                verbose_name="sequence features",
            ),
        ),
        migrations.AlterField(
            model_name="sacerevisiaestrain",
            name="sequence_features",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when a feature is not present in the chosen plasmid(s), if any. Searching against the aliases of a feature is case-sensitive. <a href="/formz/sequencefeature/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_features",
                to="formz.sequencefeature",
                verbose_name="sequence features",
            ),
        ),
        migrations.AlterField(
            model_name="scpombestrain",
            name="sequence_features",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when a feature is not present in the chosen plasmid(s), if any. Searching against the aliases of a feature is case-sensitive. <a href="/formz/sequencefeature/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_features",
                to="formz.sequencefeature",
                verbose_name="sequence features",
            ),
        ),
        migrations.AlterField(
            model_name="wormstrain",
            name="sequence_features",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when a feature is not present in the chosen plasmid(s), if any. Searching against the aliases of a feature is case-sensitive. <a href="/formz/sequencefeature/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_features",
                to="formz.sequencefeature",
                verbose_name="sequence features",
            ),
        ),
        migrations.AlterField(
            model_name="wormstrainallele",
            name="sequence_features",
            field=models.ManyToManyField(
                blank=True,
                help_text='Searching against the aliases of a sequence feature is case-sensitive. <a href="/formz/sequencefeature/" target="_blank">View all/Change</a>',
                to="formz.sequencefeature",
                verbose_name="elements",
            ),
        ),
    ]
