# Generated by Django 4.2.17 on 2025-03-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_pi",
            field=models.BooleanField(
                default=False, verbose_name="is principal investigator?"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="oidc_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="OIDC identifier",
            ),
        ),
    ]
