# Generated by Django 2.2.9 on 2020-01-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_generalsetting_site_admin_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='join_api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='join api key'),
        ),
    ]
