# Generated by Django 3.2.14 on 2022-08-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_generalsetting_ms_teams_webhook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsetting',
            name='join_api_key',
        ),
    ]
