# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-08 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pages.Tag'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pages.Tag'),
        ),
    ]
