# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_auto_20181116_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmsdsform',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalorderextradoc',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='msdsform',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderextradoc',
            name='created_by',
        ),
    ]
