# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0006_auto_20181123_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'open'), ('arranged', 'arranged')], default='open', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'open'), ('arranged', 'arranged')], default='open', max_length=255, verbose_name='Status'),
        ),
    ]
