# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0008_auto_20181123_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='delivered_date',
            field=models.DateField(blank=True, default='2018-01-01', verbose_name='Delivered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='order_manager_created_date_time',
            field=models.DateTimeField(blank=True, default='2018-01-01', verbose_name='Created in OrderManager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(blank=True, default='2018-01-01', verbose_name='Delivered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_manager_created_date_time',
            field=models.DateTimeField(blank=True, default='2018-01-01', verbose_name='Created in OrderManager'),
            preserve_default=False,
        ),
    ]
