# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0010_auto_20181123_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='msds_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_management.MsdsForm'),
        ),
    ]
