# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0011_auto_20181123_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='created_date_time',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'submitted'), ('open', 'open'), ('arranged', 'arranged'), ('delivered', 'delivered')], default='submitted', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'submitted'), ('open', 'open'), ('arranged', 'arranged'), ('delivered', 'delivered')], default='submitted', max_length=255, verbose_name='Status'),
        ),
    ]
