# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0016_auto_20181125_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='order_manager_created_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created in OrderManager'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_manager_created_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created in OrderManager'),
        ),
    ]
