# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0020_auto_20181128_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order_management.Location'),
        ),
    ]
