# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0022_auto_20181205_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('open', 'open'), ('arranged', 'arranged'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('used up', 'used up')], default='submitted', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('open', 'open'), ('arranged', 'arranged'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('used up', 'used up')], default='submitted', max_length=255, verbose_name='Status'),
        ),
    ]
