# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0023_auto_20181206_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmsdsform',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalorderextradoc',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalorderextradoc',
            name='order',
        ),
        migrations.DeleteModel(
            name='HistoricalMsdsForm',
        ),
        migrations.DeleteModel(
            name='HistoricalOrderExtraDoc',
        ),
    ]
