# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0024_auto_20181209_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderextradoc',
            name='description',
            field=models.CharField(default='test', max_length=255, verbose_name='Quantity'),
            preserve_default=False,
        ),
    ]
