# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0029_auto_20181213_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='costunit',
            name='description',
            field=models.CharField(default='0', max_length=255, unique=True, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
