# Generated by Django 2.1.8 on 2019-04-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0035_auto_20190414_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msdsform',
            name='name',
            field=models.FileField(unique=True, upload_to='order_management/msdsform/', verbose_name='File name'),
        ),
    ]
