# Generated by Django 2.1.8 on 2019-04-24 10:32

from django.db import migrations, models, connection

def alter_table(apps, schema_editor):
    query ="ALTER TABLE order_management_msdsform ADD UNIQUE (name);"
    cursor = connection.cursor()
    cursor.execute(query)
    cursor.close()

class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0036_auto_20190424_1232'),
    ]

    operations = [migrations.RunPython(alter_table),]
