# Generated by Django 2.1.8 on 2019-07-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0040_auto_20190531_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costunit',
            name='status',
            field=models.BooleanField(default=False, null=True, verbose_name='deactivate?'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='created_date_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='delivered_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='delivered'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='delivery_alert',
            field=models.BooleanField(default=False, null=True, verbose_name='delivery notification?'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='internal_order_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='internal order number'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='last_changed_date_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='order_manager_created_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='created in OrderManager'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='part_description',
            field=models.CharField(max_length=255, verbose_name='part description'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='price',
            field=models.CharField(blank=True, max_length=255, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='quantity',
            field=models.CharField(max_length=255, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('open', 'open'), ('arranged', 'arranged'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('used up', 'used up')], default='submitted', max_length=255, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='supplier',
            field=models.CharField(max_length=255, verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='supplier_part_no',
            field=models.CharField(max_length=255, verbose_name='supplier Part-No'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='urgent',
            field=models.BooleanField(default=False, null=True, verbose_name='is this an urgent order?'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.BooleanField(default=False, null=True, verbose_name='deactivate?'),
        ),
        migrations.AlterField(
            model_name='msdsform',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='msdsform',
            name='last_changed_date_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='msdsform',
            name='name',
            field=models.FileField(unique=True, upload_to='order_management/msdsform/', verbose_name='file name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='delivered'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_alert',
            field=models.BooleanField(default=False, null=True, verbose_name='delivery notification?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='internal_order_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='internal order number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_changed_date_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_manager_created_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='created in OrderManager'),
        ),
        migrations.AlterField(
            model_name='order',
            name='part_description',
            field=models.CharField(max_length=255, verbose_name='part description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, max_length=255, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(max_length=255, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('open', 'open'), ('arranged', 'arranged'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('used up', 'used up')], default='submitted', max_length=255, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.CharField(max_length=255, verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier_part_no',
            field=models.CharField(max_length=255, verbose_name='supplier Part-No'),
        ),
        migrations.AlterField(
            model_name='order',
            name='urgent',
            field=models.BooleanField(default=False, null=True, verbose_name='is this an urgent order?'),
        ),
        migrations.AlterField(
            model_name='orderextradoc',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='orderextradoc',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='orderextradoc',
            name='last_changed_date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last changed'),
        ),
        migrations.AlterField(
            model_name='orderextradoc',
            name='name',
            field=models.FileField(upload_to='temp/', verbose_name='file name'),
        ),
    ]
