# Generated by Django 2.1.13 on 2019-11-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0046_auto_20191106_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='hazard_level_pregnancy',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('orange', 'orange'), ('red', 'red')], default='none', max_length=255, verbose_name='Hazard level for pregnancy'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hazard_level_pregnancy',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('orange', 'orange'), ('red', 'red')], default='none', max_length=255, verbose_name='Hazard level for pregnancy'),
        ),
    ]
