# Generated by Django 3.2.15 on 2022-09-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0052_auto_20210511_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='msdsform',
            name='label',
            field=models.CharField(blank=True, max_length=255, verbose_name='label'),
        ),
    ]
