# Generated by Django 3.2.15 on 2022-12-19 12:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0054_auto_20221217_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='history_ghs_symbols',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='GHS symbols'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='history_signal_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='signal words'),
        ),
        migrations.AlterField(
            model_name='order',
            name='history_ghs_symbols',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='GHS symbols'),
        ),
        migrations.AlterField(
            model_name='order',
            name='history_signal_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='signal words'),
        ),
    ]
