# Generated by Django 2.1.8 on 2019-09-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_auto_20190915_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordtobeapproved',
            old_name='message_date',
            new_name='message_date_time',
        ),
    ]
