# Generated by Django 2.1.8 on 2019-09-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0005_auto_20190915_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordtobeapproved',
            name='message',
            field=models.TextField(blank=True, max_length=255, verbose_name='message'),
        ),
    ]
