# Generated by Django 4.2.17 on 2025-03-05 10:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("approval", "0007_auto_20190917_1130"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RecordToBeApproved",
            new_name="Approval",
        ),
        migrations.AlterModelOptions(
            name="approval",
            options={"verbose_name": "approval", "verbose_name_plural": "approvals"},
        ),
    ]
