# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labuser',
            name='abbreviation_code',
        ),
        migrations.RemoveField(
            model_name='labuser',
            name='personal_order_list_url',
        ),
    ]
