# Generated by Django 2.1.8 on 2019-09-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_user', '0003_auto_20190417_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='labuser',
            name='is_principal_investigator',
            field=models.BooleanField(default=False, verbose_name='is principal investigator?'),
        ),
    ]
