# Generated by Django 2.1.13 on 2019-11-24 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsetting',
            name='site_admin_email_address',
        ),
    ]
