# Generated by Django 2.1.8 on 2019-09-14 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordToBeApproved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('activity_type', models.CharField(choices=[('created', 'created'), ('changed', 'changed')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='message')),
                ('message_date', models.DateField(blank=True, null=True)),
                ('edited', models.BooleanField(blank=True, verbose_name='edited?')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('activity_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'record to be approved',
                'verbose_name_plural': 'records to be approved',
            },
        ),
    ]
