# Generated by Django 2.1.8 on 2019-09-15 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_approval', '0004_auto_20190915_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordtobeapproved',
            old_name='date',
            new_name='created_date_time',
        ),
    ]
