# Generated by Django 2.0.13 on 2019-04-17 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extend_user', '0002_auto_20181125_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
